import type { OperatorScopeEvidence, OperatorSnapshot } from "./contracts";

/** Deterministic account-context evidence shared by operator response fixtures. */
export function makeOperatorScopeEvidence(): OperatorScopeEvidence {
  return {
    account_ids: ["act_123"],
    display_timezone: "Europe/Kaliningrad",
    cabinet_timezone: "Europe/Kaliningrad",
    cabinet_timezone_state: "single",
    missing_timezone_account_ids: [],
    currency: "USD",
    currency_state: "single",
    missing_currency_account_ids: [],
    currency_observed_at: "2026-07-18T10:14:45Z",
  };
}

/** Deterministic contract fixture for frontend, TMA and contract tests. */
export function makeOperatorSnapshot(): OperatorSnapshot {
  return {
    meta: {
      revision: "r2a",
      sequence: 42,
      generated_at: "2026-07-18T10:15:00Z",
      timezone: "Europe/Kaliningrad",
      cabinet_timezone: "Europe/Kaliningrad",
      cabinet_timezone_known: true,
      cabinet_timezone_state: "single",
      missing_timezone_account_ids: [],
      currency: "USD",
      currency_state: "single",
      missing_currency_account_ids: [],
      currency_observed_at: "2026-07-18T10:14:45Z",
      window: "today",
      account: { id: "act_123", name: "Main cabinet" },
      cabinet_day: {
        starts_at: "2026-07-18T00:00:00+02:00",
        ends_at: "2026-07-19T00:00:00+02:00",
      },
    },
    attention: {
      state: "ready",
      as_of: "2026-07-18T10:14:45Z",
      freshness_seconds: 15,
      sources: ["observer", "tracker"],
      issues: [],
      data: {
        items: [
          {
            id: "incident-1",
            kind: "incident",
            severity: "warning",
            title: "CPL выше базы",
            summary: "CPL $9.56 при базе $3.00.",
            reason: "Расход растёт без FTD",
            occurred_at: "2026-07-18T10:10:00Z",
            target: { kind: "ad", id: "ad-1", label: "GH_CR2" },
            action: { label: "Открыть объявление", href: "/ads/ad-1" },
          },
        ],
      },
    },
    portfolio: {
      state: "partial",
      as_of: "2026-07-18T10:14:45Z",
      freshness_seconds: 255,
      sources: ["meta", "offer_rules", "meta_account_snapshot"],
      issues: [],
      data: {
        currency_groups: [
          {
            id: "USD",
            currency: "USD",
            state: "partial",
            severity: "critical",
            as_of: "2026-07-18T10:14:45Z",
            freshness_seconds: 255,
            totals: {
              spend: "47.80",
              base: "39.00",
              stop: "45.00",
              base_delta: "8.80",
            },
            cabinets: [
              {
                id: "123",
                name: "GH_CR2",
                timezone: "Africa/Accra",
                currency: "USD",
                state: "ready",
                severity: "critical",
                as_of: "2026-07-18T10:14:45Z",
                freshness_seconds: 15,
                cabinet_day: {
                  starts_at: "2026-07-18T00:00:00Z",
                  ends_at: "2026-07-19T00:00:00Z",
                },
                totals: {
                  spend: "18.40",
                  base: "15.00",
                  stop: "18.00",
                  base_delta: "3.40",
                },
                risk_label: "Stop превышен",
                risk_reason: "Факт $18.40 ≥ stop $18.00",
                issues: [],
                action: { label: "Открыть кабинет", href: "/cabinets/123" },
              },
              {
                id: "456",
                name: "PL_VIP",
                timezone: "Europe/Warsaw",
                currency: "USD",
                state: "ready",
                severity: "ok",
                as_of: "2026-07-18T10:14:40Z",
                freshness_seconds: 20,
                cabinet_day: {
                  starts_at: "2026-07-17T22:00:00Z",
                  ends_at: "2026-07-18T22:00:00Z",
                },
                totals: {
                  spend: "13.60",
                  base: "15.00",
                  stop: "18.00",
                  base_delta: "-1.40",
                },
                risk_label: "В пределах порогов",
                risk_reason: "До stop осталось $4.40",
                issues: [],
                action: { label: "Открыть кабинет", href: "/cabinets/456" },
              },
              {
                id: "789",
                name: "ES_CORE",
                timezone: "Europe/Madrid",
                currency: "USD",
                state: "stale",
                severity: "unknown",
                as_of: "2026-07-18T10:10:45Z",
                freshness_seconds: 255,
                cabinet_day: {
                  starts_at: "2026-07-17T22:00:00Z",
                  ends_at: "2026-07-18T22:00:00Z",
                },
                totals: {
                  spend: "15.80",
                  base: "9.00",
                  stop: "9.00",
                  base_delta: "6.80",
                },
                risk_label: "Снимок устарел",
                risk_reason: "Последний полный снимок был 4 минуты назад.",
                issues: [],
                action: { label: "Открыть кабинет", href: "/cabinets/789" },
              },
            ],
          },
        ],
      },
    },
    economy: {
      state: "ready",
      as_of: "2026-07-18T10:14:45Z",
      freshness_seconds: 15,
      sources: ["meta"],
      issues: [],
      data: {
        totals: {
          spend: "18.40",
          base: "15.00",
          stop: "30.00",
          base_delta: "3.40",
        },
        series: [
          {
            at: "2026-07-18T08:00:00Z",
            actual: "4.20",
            base: "5.00",
            stop: "10.00",
          },
          {
            at: "2026-07-18T09:00:00Z",
            actual: null,
            base: "10.00",
            stop: "20.00",
          },
          {
            at: "2026-07-18T10:00:00Z",
            actual: "18.40",
            base: "15.00",
            stop: "30.00",
          },
        ],
      },
    },
    funnel: {
      state: "ready",
      as_of: "2026-07-18T10:14:45Z",
      freshness_seconds: 15,
      sources: ["meta", "tracker"],
      issues: [],
      data: {
        stages: [
          {
            key: "clicks",
            label: "Клики",
            count: 42,
            conversion: "100",
            cost: "0.44",
          },
          {
            key: "registrations",
            label: "Регистрации",
            count: 5,
            conversion: "11.90",
            cost: "3.68",
          },
          {
            key: "ftd",
            label: "FTD",
            count: 1,
            conversion: "20.00",
            cost: "18.40",
          },
          {
            key: "confirmed_deposits",
            label: "Подтверждённые депозиты",
            count: 1,
            conversion: "100",
            cost: "18.40",
          },
        ],
      },
    },
    // Пустой список — подтверждённое «ничего не подходит к стопу», поэтому
    // state=empty, а не unavailable.
    approaching_stop: {
      state: "empty",
      as_of: "2026-07-18T10:14:45Z",
      freshness_seconds: 15,
      sources: ["observer"],
      issues: [],
      data: { items: [] },
    },
    actions: {
      state: "ready",
      as_of: "2026-07-18T10:14:45Z",
      freshness_seconds: 15,
      sources: ["task_queue"],
      issues: [],
      data: {
        items: [
          {
            id: "1842",
            public_id: "#1842",
            kind: "pause",
            state: "running",
            title: "Отключение объявления",
            target_label: "GH_CR2",
            requested_at: "2026-07-18T10:12:00Z",
            updated_at: "2026-07-18T10:13:00Z",
            requested_by: "operator",
            reason: null,
            correlation_id: "corr-1",
            account_id: "act_123",
            currency: "USD",
            cabinet_timezone: "Europe/Kaliningrad",
            account_context_observed_at: "2026-07-18T10:14:45Z",
            account_context_issues: [],
          },
        ],
      },
    },
    system: {
      state: "ready",
      as_of: "2026-07-18T10:14:45Z",
      freshness_seconds: 15,
      sources: ["postgresql", "cabinet_runtime"],
      issues: [],
      data: {
        severity: "warning",
        monitoring_enabled: true,
        last_scan_at: "2026-07-18T10:14:30Z",
        next_scan_at: "2026-07-18T10:15:00Z",
        workers: [
          {
            id: "observer",
            label: "Observer",
            severity: "ok",
            status: "online",
            last_activity_at: "2026-07-18T10:14:45Z",
          },
          {
            id: "browser",
            label: "Browser agent",
            severity: "warning",
            status: "degraded",
            last_activity_at: "2026-07-18T10:14:40Z",
          },
        ],
      },
    },
  };
}
