/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ScriptsIndexRouteImport } from './routes/scripts/index'
import { Route as OffersIndexRouteImport } from './routes/offers/index'
import { Route as HistoryIndexRouteImport } from './routes/history/index'
import { Route as HealthIndexRouteImport } from './routes/health/index'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns/index'
import { Route as AdsIndexRouteImport } from './routes/ads/index'
import { Route as AdsFbAdIdRouteImport } from './routes/ads/$fbAdId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptsIndexRoute = ScriptsIndexRouteImport.update({
  id: '/scripts/',
  path: '/scripts/',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersIndexRoute = OffersIndexRouteImport.update({
  id: '/offers/',
  path: '/offers/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthIndexRoute = HealthIndexRouteImport.update({
  id: '/health/',
  path: '/health/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsIndexRoute = AdsIndexRouteImport.update({
  id: '/ads/',
  path: '/ads/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsFbAdIdRoute = AdsFbAdIdRouteImport.update({
  id: '/ads/$fbAdId',
  path: '/ads/$fbAdId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ads/$fbAdId': typeof AdsFbAdIdRoute
  '/ads/': typeof AdsIndexRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/health/': typeof HealthIndexRoute
  '/history/': typeof HistoryIndexRoute
  '/offers/': typeof OffersIndexRoute
  '/scripts/': typeof ScriptsIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ads/$fbAdId': typeof AdsFbAdIdRoute
  '/ads': typeof AdsIndexRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/health': typeof HealthIndexRoute
  '/history': typeof HistoryIndexRoute
  '/offers': typeof OffersIndexRoute
  '/scripts': typeof ScriptsIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ads/$fbAdId': typeof AdsFbAdIdRoute
  '/ads/': typeof AdsIndexRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/health/': typeof HealthIndexRoute
  '/history/': typeof HistoryIndexRoute
  '/offers/': typeof OffersIndexRoute
  '/scripts/': typeof ScriptsIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ads/$fbAdId'
    | '/ads/'
    | '/campaigns/'
    | '/health/'
    | '/history/'
    | '/offers/'
    | '/scripts/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ads/$fbAdId'
    | '/ads'
    | '/campaigns'
    | '/health'
    | '/history'
    | '/offers'
    | '/scripts'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/ads/$fbAdId'
    | '/ads/'
    | '/campaigns/'
    | '/health/'
    | '/history/'
    | '/offers/'
    | '/scripts/'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdsFbAdIdRoute: typeof AdsFbAdIdRoute
  AdsIndexRoute: typeof AdsIndexRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
  HealthIndexRoute: typeof HealthIndexRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
  OffersIndexRoute: typeof OffersIndexRoute
  ScriptsIndexRoute: typeof ScriptsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts/': {
      id: '/scripts/'
      path: '/scripts'
      fullPath: '/scripts/'
      preLoaderRoute: typeof ScriptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers/': {
      id: '/offers/'
      path: '/offers'
      fullPath: '/offers/'
      preLoaderRoute: typeof OffersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/': {
      id: '/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof HistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health/': {
      id: '/health/'
      path: '/health'
      fullPath: '/health/'
      preLoaderRoute: typeof HealthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads/': {
      id: '/ads/'
      path: '/ads'
      fullPath: '/ads/'
      preLoaderRoute: typeof AdsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads/$fbAdId': {
      id: '/ads/$fbAdId'
      path: '/ads/$fbAdId'
      fullPath: '/ads/$fbAdId'
      preLoaderRoute: typeof AdsFbAdIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdsFbAdIdRoute: AdsFbAdIdRoute,
  AdsIndexRoute: AdsIndexRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
  HealthIndexRoute: HealthIndexRoute,
  HistoryIndexRoute: HistoryIndexRoute,
  OffersIndexRoute: OffersIndexRoute,
  ScriptsIndexRoute: ScriptsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
