/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OpenRouteImport } from './routes/open'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as OffersIndexRouteImport } from './routes/offers/index'
import { Route as IncidentsIndexRouteImport } from './routes/incidents/index'
import { Route as DesktopIndexRouteImport } from './routes/desktop/index'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns/index'
import { Route as AnalyticsIndexRouteImport } from './routes/analytics/index'
import { Route as AdsIndexRouteImport } from './routes/ads/index'
import { Route as ActionsIndexRouteImport } from './routes/actions/index'
import { Route as SystemSourcesRouteImport } from './routes/system/sources'
import { Route as SettingsVisionRouteImport } from './routes/settings/vision'
import { Route as SettingsTelegramRouteImport } from './routes/settings/telegram'
import { Route as SettingsObserverRouteImport } from './routes/settings/observer'
import { Route as SettingsDisplayRouteImport } from './routes/settings/display'
import { Route as IncidentsIncidentIdRouteImport } from './routes/incidents/$incidentId'
import { Route as CabinetsCabinetIdRouteImport } from './routes/cabinets/$cabinetId'
import { Route as AdsFbAdIdRouteImport } from './routes/ads/$fbAdId'
import { Route as ActionsActionIdRouteImport } from './routes/actions/$actionId'
import { Route as CampaignsPresetsIndexRouteImport } from './routes/campaigns/presets/index'
import { Route as CampaignsCreateIndexRouteImport } from './routes/campaigns/create/index'

const OpenRoute = OpenRouteImport.update({
  id: '/open',
  path: '/open',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersIndexRoute = OffersIndexRouteImport.update({
  id: '/offers/',
  path: '/offers/',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsIndexRoute = IncidentsIndexRouteImport.update({
  id: '/incidents/',
  path: '/incidents/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesktopIndexRoute = DesktopIndexRouteImport.update({
  id: '/desktop/',
  path: '/desktop/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsIndexRoute = AnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsIndexRoute = AdsIndexRouteImport.update({
  id: '/ads/',
  path: '/ads/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsIndexRoute = ActionsIndexRouteImport.update({
  id: '/actions/',
  path: '/actions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemSourcesRoute = SystemSourcesRouteImport.update({
  id: '/system/sources',
  path: '/system/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsVisionRoute = SettingsVisionRouteImport.update({
  id: '/settings/vision',
  path: '/settings/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTelegramRoute = SettingsTelegramRouteImport.update({
  id: '/settings/telegram',
  path: '/settings/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsObserverRoute = SettingsObserverRouteImport.update({
  id: '/settings/observer',
  path: '/settings/observer',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsDisplayRoute = SettingsDisplayRouteImport.update({
  id: '/settings/display',
  path: '/settings/display',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsIncidentIdRoute = IncidentsIncidentIdRouteImport.update({
  id: '/incidents/$incidentId',
  path: '/incidents/$incidentId',
  getParentRoute: () => rootRouteImport,
} as any)
const CabinetsCabinetIdRoute = CabinetsCabinetIdRouteImport.update({
  id: '/cabinets/$cabinetId',
  path: '/cabinets/$cabinetId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsFbAdIdRoute = AdsFbAdIdRouteImport.update({
  id: '/ads/$fbAdId',
  path: '/ads/$fbAdId',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsActionIdRoute = ActionsActionIdRouteImport.update({
  id: '/actions/$actionId',
  path: '/actions/$actionId',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsPresetsIndexRoute = CampaignsPresetsIndexRouteImport.update({
  id: '/campaigns/presets/',
  path: '/campaigns/presets/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCreateIndexRoute = CampaignsCreateIndexRouteImport.update({
  id: '/campaigns/create/',
  path: '/campaigns/create/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/open': typeof OpenRoute
  '/actions/$actionId': typeof ActionsActionIdRoute
  '/ads/$fbAdId': typeof AdsFbAdIdRoute
  '/cabinets/$cabinetId': typeof CabinetsCabinetIdRoute
  '/incidents/$incidentId': typeof IncidentsIncidentIdRoute
  '/settings/display': typeof SettingsDisplayRoute
  '/settings/observer': typeof SettingsObserverRoute
  '/settings/telegram': typeof SettingsTelegramRoute
  '/settings/vision': typeof SettingsVisionRoute
  '/system/sources': typeof SystemSourcesRoute
  '/actions/': typeof ActionsIndexRoute
  '/ads/': typeof AdsIndexRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/desktop/': typeof DesktopIndexRoute
  '/incidents/': typeof IncidentsIndexRoute
  '/offers/': typeof OffersIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/campaigns/create/': typeof CampaignsCreateIndexRoute
  '/campaigns/presets/': typeof CampaignsPresetsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/open': typeof OpenRoute
  '/actions/$actionId': typeof ActionsActionIdRoute
  '/ads/$fbAdId': typeof AdsFbAdIdRoute
  '/cabinets/$cabinetId': typeof CabinetsCabinetIdRoute
  '/incidents/$incidentId': typeof IncidentsIncidentIdRoute
  '/settings/display': typeof SettingsDisplayRoute
  '/settings/observer': typeof SettingsObserverRoute
  '/settings/telegram': typeof SettingsTelegramRoute
  '/settings/vision': typeof SettingsVisionRoute
  '/system/sources': typeof SystemSourcesRoute
  '/actions': typeof ActionsIndexRoute
  '/ads': typeof AdsIndexRoute
  '/analytics': typeof AnalyticsIndexRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/desktop': typeof DesktopIndexRoute
  '/incidents': typeof IncidentsIndexRoute
  '/offers': typeof OffersIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/campaigns/create': typeof CampaignsCreateIndexRoute
  '/campaigns/presets': typeof CampaignsPresetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/open': typeof OpenRoute
  '/actions/$actionId': typeof ActionsActionIdRoute
  '/ads/$fbAdId': typeof AdsFbAdIdRoute
  '/cabinets/$cabinetId': typeof CabinetsCabinetIdRoute
  '/incidents/$incidentId': typeof IncidentsIncidentIdRoute
  '/settings/display': typeof SettingsDisplayRoute
  '/settings/observer': typeof SettingsObserverRoute
  '/settings/telegram': typeof SettingsTelegramRoute
  '/settings/vision': typeof SettingsVisionRoute
  '/system/sources': typeof SystemSourcesRoute
  '/actions/': typeof ActionsIndexRoute
  '/ads/': typeof AdsIndexRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/desktop/': typeof DesktopIndexRoute
  '/incidents/': typeof IncidentsIndexRoute
  '/offers/': typeof OffersIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/campaigns/create/': typeof CampaignsCreateIndexRoute
  '/campaigns/presets/': typeof CampaignsPresetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/open'
    | '/actions/$actionId'
    | '/ads/$fbAdId'
    | '/cabinets/$cabinetId'
    | '/incidents/$incidentId'
    | '/settings/display'
    | '/settings/observer'
    | '/settings/telegram'
    | '/settings/vision'
    | '/system/sources'
    | '/actions/'
    | '/ads/'
    | '/analytics/'
    | '/campaigns/'
    | '/desktop/'
    | '/incidents/'
    | '/offers/'
    | '/settings/'
    | '/campaigns/create/'
    | '/campaigns/presets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/open'
    | '/actions/$actionId'
    | '/ads/$fbAdId'
    | '/cabinets/$cabinetId'
    | '/incidents/$incidentId'
    | '/settings/display'
    | '/settings/observer'
    | '/settings/telegram'
    | '/settings/vision'
    | '/system/sources'
    | '/actions'
    | '/ads'
    | '/analytics'
    | '/campaigns'
    | '/desktop'
    | '/incidents'
    | '/offers'
    | '/settings'
    | '/campaigns/create'
    | '/campaigns/presets'
  id:
    | '__root__'
    | '/'
    | '/open'
    | '/actions/$actionId'
    | '/ads/$fbAdId'
    | '/cabinets/$cabinetId'
    | '/incidents/$incidentId'
    | '/settings/display'
    | '/settings/observer'
    | '/settings/telegram'
    | '/settings/vision'
    | '/system/sources'
    | '/actions/'
    | '/ads/'
    | '/analytics/'
    | '/campaigns/'
    | '/desktop/'
    | '/incidents/'
    | '/offers/'
    | '/settings/'
    | '/campaigns/create/'
    | '/campaigns/presets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OpenRoute: typeof OpenRoute
  ActionsActionIdRoute: typeof ActionsActionIdRoute
  AdsFbAdIdRoute: typeof AdsFbAdIdRoute
  CabinetsCabinetIdRoute: typeof CabinetsCabinetIdRoute
  IncidentsIncidentIdRoute: typeof IncidentsIncidentIdRoute
  SettingsDisplayRoute: typeof SettingsDisplayRoute
  SettingsObserverRoute: typeof SettingsObserverRoute
  SettingsTelegramRoute: typeof SettingsTelegramRoute
  SettingsVisionRoute: typeof SettingsVisionRoute
  SystemSourcesRoute: typeof SystemSourcesRoute
  ActionsIndexRoute: typeof ActionsIndexRoute
  AdsIndexRoute: typeof AdsIndexRoute
  AnalyticsIndexRoute: typeof AnalyticsIndexRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
  DesktopIndexRoute: typeof DesktopIndexRoute
  IncidentsIndexRoute: typeof IncidentsIndexRoute
  OffersIndexRoute: typeof OffersIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  CampaignsCreateIndexRoute: typeof CampaignsCreateIndexRoute
  CampaignsPresetsIndexRoute: typeof CampaignsPresetsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/open': {
      id: '/open'
      path: '/open'
      fullPath: '/open'
      preLoaderRoute: typeof OpenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers/': {
      id: '/offers/'
      path: '/offers'
      fullPath: '/offers/'
      preLoaderRoute: typeof OffersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents/': {
      id: '/incidents/'
      path: '/incidents'
      fullPath: '/incidents/'
      preLoaderRoute: typeof IncidentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desktop/': {
      id: '/desktop/'
      path: '/desktop'
      fullPath: '/desktop/'
      preLoaderRoute: typeof DesktopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/': {
      id: '/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads/': {
      id: '/ads/'
      path: '/ads'
      fullPath: '/ads/'
      preLoaderRoute: typeof AdsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions/': {
      id: '/actions/'
      path: '/actions'
      fullPath: '/actions/'
      preLoaderRoute: typeof ActionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/sources': {
      id: '/system/sources'
      path: '/system/sources'
      fullPath: '/system/sources'
      preLoaderRoute: typeof SystemSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/vision': {
      id: '/settings/vision'
      path: '/settings/vision'
      fullPath: '/settings/vision'
      preLoaderRoute: typeof SettingsVisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/telegram': {
      id: '/settings/telegram'
      path: '/settings/telegram'
      fullPath: '/settings/telegram'
      preLoaderRoute: typeof SettingsTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/observer': {
      id: '/settings/observer'
      path: '/settings/observer'
      fullPath: '/settings/observer'
      preLoaderRoute: typeof SettingsObserverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/display': {
      id: '/settings/display'
      path: '/settings/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof SettingsDisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents/$incidentId': {
      id: '/incidents/$incidentId'
      path: '/incidents/$incidentId'
      fullPath: '/incidents/$incidentId'
      preLoaderRoute: typeof IncidentsIncidentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabinets/$cabinetId': {
      id: '/cabinets/$cabinetId'
      path: '/cabinets/$cabinetId'
      fullPath: '/cabinets/$cabinetId'
      preLoaderRoute: typeof CabinetsCabinetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads/$fbAdId': {
      id: '/ads/$fbAdId'
      path: '/ads/$fbAdId'
      fullPath: '/ads/$fbAdId'
      preLoaderRoute: typeof AdsFbAdIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions/$actionId': {
      id: '/actions/$actionId'
      path: '/actions/$actionId'
      fullPath: '/actions/$actionId'
      preLoaderRoute: typeof ActionsActionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/presets/': {
      id: '/campaigns/presets/'
      path: '/campaigns/presets'
      fullPath: '/campaigns/presets/'
      preLoaderRoute: typeof CampaignsPresetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/create/': {
      id: '/campaigns/create/'
      path: '/campaigns/create'
      fullPath: '/campaigns/create/'
      preLoaderRoute: typeof CampaignsCreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OpenRoute: OpenRoute,
  ActionsActionIdRoute: ActionsActionIdRoute,
  AdsFbAdIdRoute: AdsFbAdIdRoute,
  CabinetsCabinetIdRoute: CabinetsCabinetIdRoute,
  IncidentsIncidentIdRoute: IncidentsIncidentIdRoute,
  SettingsDisplayRoute: SettingsDisplayRoute,
  SettingsObserverRoute: SettingsObserverRoute,
  SettingsTelegramRoute: SettingsTelegramRoute,
  SettingsVisionRoute: SettingsVisionRoute,
  SystemSourcesRoute: SystemSourcesRoute,
  ActionsIndexRoute: ActionsIndexRoute,
  AdsIndexRoute: AdsIndexRoute,
  AnalyticsIndexRoute: AnalyticsIndexRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
  DesktopIndexRoute: DesktopIndexRoute,
  IncidentsIndexRoute: IncidentsIndexRoute,
  OffersIndexRoute: OffersIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  CampaignsCreateIndexRoute: CampaignsCreateIndexRoute,
  CampaignsPresetsIndexRoute: CampaignsPresetsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
