"""creator plan columns

Revision ID: 091a639e018a
Revises: c8d9e0f1a2b3
Create Date: 2026-05-15 21:09:15.381564
"""

from __future__ import annotations

from typing import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "091a639e018a"
down_revision: str | None = "c8d9e0f1a2b3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("campaign_creator_tasks", sa.Column("spec_json", sa.JSON(), nullable=True))
    op.add_column("campaign_creator_tasks", sa.Column("plan_json", sa.JSON(), nullable=True))
    op.add_column(
        "campaign_creator_tasks",
        sa.Column("progress_index", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column("campaign_creator_tasks", sa.Column("fb_state_json", sa.JSON(), nullable=True))
    op.add_column("campaign_creator_tasks", sa.Column("last_error_json", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("campaign_creator_tasks", "last_error_json")
    op.drop_column("campaign_creator_tasks", "fb_state_json")
    op.drop_column("campaign_creator_tasks", "progress_index")
    op.drop_column("campaign_creator_tasks", "plan_json")
    op.drop_column("campaign_creator_tasks", "spec_json")
    # ### end Alembic commands ###
