"""add_campaign_creator_task

Revision ID: 2db5dda71c17
Revises: d0e1f2a3b4c5
Create Date: 2026-05-11 20:59:57.500810
"""
from __future__ import annotations

from typing import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '2db5dda71c17'
down_revision: str | None = 'd0e1f2a3b4c5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_creator_tasks',
    sa.Column('offer_code', sa.String(length=64), nullable=False),
    sa.Column('creative_folder', sa.String(length=256), nullable=False),
    sa.Column('cabinet_id', sa.String(length=64), nullable=False),
    sa.Column('cdp_url', sa.String(length=256), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'WAITING_CONFIRMATION', 'CONFIRMED', 'SUCCEEDED', 'FAILED', 'CANCELLED', name='campaign_creator_task_status_enum'), nullable=False),
    sa.Column('current_step', sa.String(length=128), nullable=True),
    sa.Column('checkpoint_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('campaign_name', sa.String(length=256), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campaign_creator_tasks')
    # ### end Alembic commands ###
