"""add_ai_cache_table

Revision ID: 6ada1843542c
Revises: c1d2e3f4a5b6
Create Date: 2026-05-19 20:13:42.381403
"""

from __future__ import annotations

from typing import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "6ada1843542c"
down_revision: str | None = "c1d2e3f4a5b6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_cache",
        sa.Column("block_type", sa.String(length=50), nullable=False),
        sa.Column("scope_key", sa.String(length=255), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("tokens_in", sa.Integer(), nullable=True),
        sa.Column("tokens_out", sa.Integer(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ai_cache_block_type"), "ai_cache", ["block_type"], unique=False)
    op.create_index(op.f("ix_ai_cache_expires_at"), "ai_cache", ["expires_at"], unique=False)
    op.create_index(op.f("ix_ai_cache_scope_key"), "ai_cache", ["scope_key"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ai_cache_scope_key"), table_name="ai_cache")
    op.drop_index(op.f("ix_ai_cache_expires_at"), table_name="ai_cache")
    op.drop_index(op.f("ix_ai_cache_block_type"), table_name="ai_cache")
    op.drop_table("ai_cache")
    # ### end Alembic commands ###
