"""add_install_cost_and_agent_commission

Revision ID: 73ced3ee9742
Revises: a7f3b1c2d4e5
Create Date: 2026-04-03 16:45:57.896706
"""

from __future__ import annotations

from typing import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "73ced3ee9742"
down_revision: str | None = "a7f3b1c2d4e5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_alert_event_ad_timeline"), table_name="alert_events")
    op.create_index("ix_alert_event_created_at", "alert_events", ["created_at"], unique=False)
    op.drop_index(op.f("ix_cabinet_day_archive_range"), table_name="cabinet_day_archives")
    op.drop_index(op.f("ix_disable_task_ad_timeline"), table_name="disable_tasks")
    op.create_index("ix_disable_task_completed_at", "disable_tasks", ["completed_at"], unique=False)
    op.drop_index(op.f("ix_enable_task_ad_timeline"), table_name="enable_tasks")
    op.add_column(
        "observer_settings",
        sa.Column(
            "install_cost", sa.Numeric(precision=8, scale=4), server_default="0.02", nullable=False
        ),
    )
    op.add_column(
        "observer_settings",
        sa.Column(
            "agent_commission_percent",
            sa.Numeric(precision=6, scale=2),
            server_default="3",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("observer_settings", "agent_commission_percent")
    op.drop_column("observer_settings", "install_cost")
    op.create_index(
        op.f("ix_enable_task_ad_timeline"),
        "enable_tasks",
        ["fb_ad_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.drop_index("ix_disable_task_completed_at", table_name="disable_tasks")
    op.create_index(
        op.f("ix_disable_task_ad_timeline"),
        "disable_tasks",
        ["fb_ad_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_cabinet_day_archive_range"),
        "cabinet_day_archives",
        ["started_at", "ended_at"],
        unique=False,
    )
    op.drop_index("ix_alert_event_created_at", table_name="alert_events")
    op.create_index(
        op.f("ix_alert_event_ad_timeline"),
        "alert_events",
        ["fb_ad_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    # ### end Alembic commands ###
