"""add_enable_tasks_table

Revision ID: 87165d779b8f
Revises: df8da58e9f2c
Create Date: 2026-03-27 20:32:25.016428
"""

from __future__ import annotations

from typing import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "87165d779b8f"
down_revision: str | None = "df8da58e9f2c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "enable_tasks",
        sa.Column("snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("fb_ad_id", sa.String(length=32), nullable=False),
        sa.Column("ad_name", sa.String(length=255), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "RETRYING",
                "SUCCEEDED",
                "CANCELLED",
                "FAILED",
                name="enable_task_status_enum",
            ),
            nullable=False,
        ),
        sa.Column("requested_by_telegram_user_id", sa.String(length=64), nullable=True),
        sa.Column("requested_by_username", sa.String(length=255), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=500), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["snapshot_id"], ["ad_snapshots.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_enable_tasks_fb_ad_id"), "enable_tasks", ["fb_ad_id"], unique=False)
    op.create_index(
        op.f("ix_enable_tasks_next_retry_at"), "enable_tasks", ["next_retry_at"], unique=False
    )
    op.create_index(
        op.f("ix_enable_tasks_snapshot_id"), "enable_tasks", ["snapshot_id"], unique=False
    )
    op.create_index(op.f("ix_enable_tasks_status"), "enable_tasks", ["status"], unique=False)
    op.create_index("uq_enable_task_idempotency", "enable_tasks", ["idempotency_key"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_enable_task_idempotency", table_name="enable_tasks")
    op.drop_index(op.f("ix_enable_tasks_status"), table_name="enable_tasks")
    op.drop_index(op.f("ix_enable_tasks_snapshot_id"), table_name="enable_tasks")
    op.drop_index(op.f("ix_enable_tasks_next_retry_at"), table_name="enable_tasks")
    op.drop_index(op.f("ix_enable_tasks_fb_ad_id"), table_name="enable_tasks")
    op.drop_table("enable_tasks")
    # ### end Alembic commands ###
