"""add payout_per_deposit to offers

Revision ID: b0b55c7ebe4f
Revises: f415a2a5b060
Create Date: 2026-04-02 10:51:19.966933
"""

from __future__ import annotations

from typing import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b0b55c7ebe4f"
down_revision: str | None = "f415a2a5b060"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "offers", sa.Column("payout_per_deposit", sa.Float(), server_default="0", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("offers", "payout_per_deposit")
    # ### end Alembic commands ###
