"""initial_clean_schema

Revision ID: b2912a123fdf
Revises:
Create Date: 2026-04-03 22:26:01.832184
"""

from __future__ import annotations

from typing import Sequence

from alembic import op

revision: str = "b2912a123fdf"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_ad_deposit_corrections_ad_id"), "ad_deposit_corrections", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "ad_deposit_corrections", "fb_ads", ["ad_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(op.f("fk_alert_events_ad_id"), "alert_events", type_="foreignkey")
    op.create_foreign_key(None, "alert_events", "fb_ads", ["ad_id"], ["id"], ondelete="CASCADE")
    op.drop_constraint(op.f("fk_disable_tasks_ad_id"), "disable_tasks", type_="foreignkey")
    op.create_foreign_key(None, "disable_tasks", "fb_ads", ["ad_id"], ["id"], ondelete="CASCADE")
    op.drop_constraint(
        op.f("fk_enable_recommendation_events_ad_id"),
        "enable_recommendation_events",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "enable_recommendation_events", "fb_ads", ["ad_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(op.f("fk_enable_tasks_ad_id"), "enable_tasks", type_="foreignkey")
    op.create_foreign_key(None, "enable_tasks", "fb_ads", ["ad_id"], ["id"], ondelete="CASCADE")
    op.drop_constraint(
        op.f("fk_telegram_message_refs_ad_id"), "telegram_message_refs", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "telegram_message_refs", "fb_ads", ["ad_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "telegram_message_refs", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_telegram_message_refs_ad_id"),
        "telegram_message_refs",
        "fb_ads",
        ["ad_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(None, "enable_tasks", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_enable_tasks_ad_id"),
        "enable_tasks",
        "fb_ads",
        ["ad_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(None, "enable_recommendation_events", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_enable_recommendation_events_ad_id"),
        "enable_recommendation_events",
        "fb_ads",
        ["ad_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(None, "disable_tasks", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_disable_tasks_ad_id"),
        "disable_tasks",
        "fb_ads",
        ["ad_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(None, "alert_events", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_alert_events_ad_id"),
        "alert_events",
        "fb_ads",
        ["ad_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(None, "ad_deposit_corrections", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_ad_deposit_corrections_ad_id"),
        "ad_deposit_corrections",
        "fb_ads",
        ["ad_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
