"""initial_schema

Revision ID: d225a24ac04b
Revises:
Create Date: 2026-04-02 16:25:07.415177
"""

from __future__ import annotations

from typing import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d225a24ac04b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ad_snapshots_alert_state"), table_name="ad_snapshots")
    op.drop_index(op.f("ix_ad_snapshots_fb_ad_id"), table_name="ad_snapshots")
    op.drop_index(op.f("ix_ad_snapshots_last_observed_at"), table_name="ad_snapshots")
    op.drop_index(op.f("ix_ad_snapshots_offer_id"), table_name="ad_snapshots")
    op.create_index(
        "ix_disable_task_ad_incident",
        "disable_tasks",
        ["fb_ad_id", "open_state_token"],
        unique=False,
    )
    op.create_index(
        "ix_disable_task_queue", "disable_tasks", ["status", "next_retry_at"], unique=False
    )
    op.create_index(
        "ix_enable_task_queue", "enable_tasks", ["status", "next_retry_at"], unique=False
    )
    op.alter_column(
        "offer_rule_configs",
        "early_outbound_ctr_signal_min_percent",
        existing_type=sa.NUMERIC(precision=8, scale=2),
        type_=sa.Numeric(precision=8, scale=4),
        existing_nullable=False,
        existing_server_default=sa.text("0.80"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "offer_rule_configs",
        "early_outbound_ctr_signal_min_percent",
        existing_type=sa.Numeric(precision=8, scale=4),
        type_=sa.NUMERIC(precision=8, scale=2),
        existing_nullable=False,
        existing_server_default=sa.text("0.80"),
    )
    op.drop_index("ix_enable_task_queue", table_name="enable_tasks")
    op.drop_index("ix_disable_task_queue", table_name="disable_tasks")
    op.drop_index("ix_disable_task_ad_incident", table_name="disable_tasks")
    op.create_index(op.f("ix_ad_snapshots_offer_id"), "ad_snapshots", ["offer_id"], unique=False)
    op.create_index(
        op.f("ix_ad_snapshots_last_observed_at"), "ad_snapshots", ["last_observed_at"], unique=False
    )
    op.create_index(op.f("ix_ad_snapshots_fb_ad_id"), "ad_snapshots", ["fb_ad_id"], unique=False)
    op.create_index(
        op.f("ix_ad_snapshots_alert_state"), "ad_snapshots", ["alert_state"], unique=False
    )
    # ### end Alembic commands ###
