"""add_snoozed_until_to_ad_snapshots

Revision ID: df8da58e9f2c
Revises: 007
Create Date: 2026-03-27 20:09:58.738797
"""
from __future__ import annotations

from typing import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'df8da58e9f2c'
down_revision: str | None = '007'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ad_snapshots', sa.Column('snoozed_until', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('telegram_settings', 'pending_codes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('telegram_settings', 'pending_codes',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_column('ad_snapshots', 'snoozed_until')
    # ### end Alembic commands ###
