"""drop_cdp_url_from_campaign_creator_task

Revision ID: ef62b11fe078
Revises: 2db5dda71c17
Create Date: 2026-05-11 21:38:13.196066
"""
from __future__ import annotations

from typing import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'ef62b11fe078'
down_revision: str | None = '2db5dda71c17'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign_creator_tasks', 'cdp_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign_creator_tasks', sa.Column('cdp_url', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
