"""remove_early_signal_from_enum

Revision ID: f3facad02893
Revises: e5f6a7b8c9d0
Create Date: 2026-04-23 23:17:05.962738
"""

from __future__ import annotations

from typing import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "f3facad02893"
down_revision: str | None = "e5f6a7b8c9d0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Переводим EARLY_SIGNAL → WARNING и удаляем значение из enum
    op.execute(
        "UPDATE enable_recommendation_events SET recommendation_level = 'WARNING' WHERE recommendation_level = 'EARLY_SIGNAL'"
    )
    op.execute(
        "ALTER TYPE enable_recommendation_level_enum RENAME TO enable_recommendation_level_enum_old"
    )
    op.execute("CREATE TYPE enable_recommendation_level_enum AS ENUM ('OK', 'WARNING')")
    op.execute("""
        ALTER TABLE enable_recommendation_events
        ALTER COLUMN recommendation_level TYPE enable_recommendation_level_enum
        USING recommendation_level::text::enable_recommendation_level_enum
    """)
    op.execute("DROP TYPE enable_recommendation_level_enum_old")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("ad_auto_enable_disabled_fb_ad_id_key"), "ad_auto_enable_disabled", type_="unique"
    )
    op.drop_index(op.f("ix_ad_auto_enable_disabled_fb_ad_id"), table_name="ad_auto_enable_disabled")
    op.create_index(
        op.f("ix_ad_auto_enable_disabled_fb_ad_id"),
        "ad_auto_enable_disabled",
        ["fb_ad_id"],
        unique=True,
    )
    op.drop_constraint(
        op.f("fk_ad_deposit_corrections_ad_id"), "ad_deposit_corrections", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "ad_deposit_corrections", "fb_ads", ["ad_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("ad_snapshots", "early_signal_rule_codes")
    op.drop_constraint(op.f("fk_alert_events_ad_id"), "alert_events", type_="foreignkey")
    op.create_foreign_key(None, "alert_events", "fb_ads", ["ad_id"], ["id"], ondelete="CASCADE")
    op.drop_constraint(op.f("fk_disable_tasks_ad_id"), "disable_tasks", type_="foreignkey")
    op.create_foreign_key(None, "disable_tasks", "fb_ads", ["ad_id"], ["id"], ondelete="CASCADE")
    op.drop_constraint(
        op.f("fk_enable_recommendation_events_ad_id"),
        "enable_recommendation_events",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "enable_recommendation_events", "fb_ads", ["ad_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(op.f("fk_enable_tasks_ad_id"), "enable_tasks", type_="foreignkey")
    op.create_foreign_key(None, "enable_tasks", "fb_ads", ["ad_id"], ["id"], ondelete="CASCADE")
    op.alter_column(
        "fb_adsets",
        "first_seen_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "fb_adsets",
        "last_seen_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "fb_adsets",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "fb_adsets",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "fb_campaigns",
        "first_seen_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "fb_campaigns",
        "last_seen_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "fb_campaigns",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "fb_campaigns",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("offer_rule_configs", "early_outbound_ctr_signal_min_percent")
    op.drop_column("offer_rule_configs", "early_lpv_ratio_signal_enabled")
    op.drop_column("offer_rule_configs", "early_lpv_ratio_signal_min_percent")
    op.drop_column("offer_rule_configs", "early_outbound_ctr_signal_min_spend_percent")
    op.drop_column("offer_rule_configs", "early_cost_per_lpv_signal_min_views")
    op.drop_column("offer_rule_configs", "early_lpv_ratio_signal_min_outbound_clicks")
    op.drop_column("offer_rule_configs", "early_cost_per_lpv_signal_percent_of_cpa")
    op.drop_column("offer_rule_configs", "early_outbound_ctr_signal_enabled")
    op.drop_column("offer_rule_configs", "early_cost_per_lpv_signal_enabled")
    op.drop_constraint(
        op.f("fk_telegram_message_refs_ad_id"), "telegram_message_refs", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "telegram_message_refs", "fb_ads", ["ad_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("telegram_settings", "early_topic_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "telegram_settings",
        sa.Column("early_topic_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "telegram_message_refs", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_telegram_message_refs_ad_id"),
        "telegram_message_refs",
        "fb_ads",
        ["ad_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "offer_rule_configs",
        sa.Column(
            "early_cost_per_lpv_signal_enabled",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "offer_rule_configs",
        sa.Column(
            "early_outbound_ctr_signal_enabled",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "offer_rule_configs",
        sa.Column(
            "early_cost_per_lpv_signal_percent_of_cpa",
            sa.NUMERIC(precision=8, scale=2),
            server_default=sa.text("'5'::numeric"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "offer_rule_configs",
        sa.Column(
            "early_lpv_ratio_signal_min_outbound_clicks",
            sa.INTEGER(),
            server_default=sa.text("5"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "offer_rule_configs",
        sa.Column(
            "early_cost_per_lpv_signal_min_views",
            sa.INTEGER(),
            server_default=sa.text("2"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "offer_rule_configs",
        sa.Column(
            "early_outbound_ctr_signal_min_spend_percent",
            sa.NUMERIC(precision=8, scale=2),
            server_default=sa.text("'5'::numeric"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "offer_rule_configs",
        sa.Column(
            "early_lpv_ratio_signal_min_percent",
            sa.NUMERIC(precision=8, scale=2),
            server_default=sa.text("'60'::numeric"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "offer_rule_configs",
        sa.Column(
            "early_lpv_ratio_signal_enabled",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "offer_rule_configs",
        sa.Column(
            "early_outbound_ctr_signal_min_percent",
            sa.NUMERIC(precision=8, scale=4),
            server_default=sa.text("0.80"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.alter_column(
        "fb_campaigns",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "fb_campaigns",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "fb_campaigns",
        "last_seen_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "fb_campaigns",
        "first_seen_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "fb_adsets",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "fb_adsets",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "fb_adsets",
        "last_seen_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "fb_adsets",
        "first_seen_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.drop_constraint(None, "enable_tasks", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_enable_tasks_ad_id"),
        "enable_tasks",
        "fb_ads",
        ["ad_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(None, "enable_recommendation_events", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_enable_recommendation_events_ad_id"),
        "enable_recommendation_events",
        "fb_ads",
        ["ad_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(None, "disable_tasks", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_disable_tasks_ad_id"),
        "disable_tasks",
        "fb_ads",
        ["ad_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(None, "alert_events", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_alert_events_ad_id"),
        "alert_events",
        "fb_ads",
        ["ad_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "ad_snapshots",
        sa.Column(
            "early_signal_rule_codes",
            postgresql.JSON(astext_type=sa.Text()),
            server_default=sa.text("'[]'::json"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "ad_deposit_corrections", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_ad_deposit_corrections_ad_id"),
        "ad_deposit_corrections",
        "fb_ads",
        ["ad_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_index(op.f("ix_ad_auto_enable_disabled_fb_ad_id"), table_name="ad_auto_enable_disabled")
    op.create_index(
        op.f("ix_ad_auto_enable_disabled_fb_ad_id"),
        "ad_auto_enable_disabled",
        ["fb_ad_id"],
        unique=False,
    )
    op.create_unique_constraint(
        op.f("ad_auto_enable_disabled_fb_ad_id_key"),
        "ad_auto_enable_disabled",
        ["fb_ad_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
