"""add_ad_snapshot_composite_indexes

Revision ID: f415a2a5b060
Revises: 018
Create Date: 2026-04-01 20:29:12.240063
"""

from __future__ import annotations

from typing import Sequence

from alembic import op

revision: str = "f415a2a5b060"
down_revision: str | None = "018"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_ad_snapshot_alert_state", "ad_snapshots", ["alert_state"], unique=False)
    op.create_index(
        "ix_ad_snapshot_last_observed",
        "ad_snapshots",
        ["last_observed_at", "alert_state"],
        unique=False,
    )
    op.create_index(
        "ix_ad_snapshot_offer_alert", "ad_snapshots", ["offer_id", "alert_state"], unique=False
    )
    op.drop_constraint(op.f("telegram_invites_code_key"), "telegram_invites", type_="unique")
    op.drop_index(op.f("ix_telegram_invites_code"), table_name="telegram_invites")
    op.create_index(op.f("ix_telegram_invites_code"), "telegram_invites", ["code"], unique=True)
    op.drop_index(op.f("ix_telegram_recipients_chat_id"), table_name="telegram_recipients")
    op.create_index(
        op.f("ix_telegram_recipients_chat_id"), "telegram_recipients", ["chat_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_telegram_recipients_chat_id"), table_name="telegram_recipients")
    op.create_index(
        op.f("ix_telegram_recipients_chat_id"), "telegram_recipients", ["chat_id"], unique=True
    )
    op.drop_index(op.f("ix_telegram_invites_code"), table_name="telegram_invites")
    op.create_index(op.f("ix_telegram_invites_code"), "telegram_invites", ["code"], unique=False)
    op.create_unique_constraint(
        op.f("telegram_invites_code_key"),
        "telegram_invites",
        ["code"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index("ix_ad_snapshot_offer_alert", table_name="ad_snapshots")
    op.drop_index("ix_ad_snapshot_last_observed", table_name="ad_snapshots")
    op.drop_index("ix_ad_snapshot_alert_state", table_name="ad_snapshots")
    # ### end Alembic commands ###
