import type { AnalyticsPerformance } from "@fb/shared";
import { makeOperatorScopeEvidence } from "@fb/shared/operator/testFixture";

export function makeAnalyticsPerformanceFixture(): AnalyticsPerformance {
  return {
    state: "ready",
    as_of: "2026-07-21T09:59:40Z",
    freshness_seconds: 20,
    issues: [],
    scope: makeOperatorScopeEvidence(),
    window: {
      from_iso: "2026-07-21T00:00:00Z",
      to_iso: "2026-07-21T10:00:00Z",
      is_live: true,
      timezone: "Europe/Kaliningrad",
      timezone_known: true,
      timezone_state: "single",
      missing_timezone_account_ids: [],
      issues: [],
      cabinet_day_note: null,
    },
    sources: {
      meta: {
        source: "meta",
        status: "good",
        last_event_at: "2026-07-21T09:59:40Z",
        lag_seconds: 20,
        unmatched_events: 0,
        timezone_known: true,
        missing_timezone_account_ids: [],
        issues: [],
        note: null,
      },
      tracker: {
        source: "tracker",
        status: "good",
        last_event_at: "2026-07-21T09:59:50Z",
        lag_seconds: 10,
        unmatched_events: 0,
        timezone_known: true,
        missing_timezone_account_ids: [],
        issues: [],
        note: null,
      },
    },
    totals: {
      spend: "18.40",
      impressions: 420,
      clicks: 42,
      leads: 5,
      registrations: 5,
      ftds: 1,
      confirmed_deposits: 1,
      redeposits: 0,
      revenue: "25.00",
      cpc: "0.4381",
      ctr_pct: "10.00",
      click_registration_cr_pct: "11.90",
      registration_ftd_cr_pct: "20.00",
      cost_per_registration: "3.6800",
      cost_per_ftd: "18.4000",
      roi_pct: "35.87",
      roas: "1.3587",
    },
    total_live_budget: {
      stage: "mixed",
      base_unit: null,
      stop_unit: null,
      quantity: null,
      base_budget: "15.00",
      stop_budget: "30.00",
      base_delta: "3.40",
      stop_delta: "-11.60",
    },
    total_budget_unavailable_reason: null,
    pagination: { page: 1, page_size: 50, total: 1, pages: 1 },
    filter_options: { accounts: [], offers: [], campaigns: [] },
    rows: [
      {
        id: "campaign-1",
        fb_id: "120001",
        name: "Campaign Alpha",
        level: "campaign",
        parent_id: null,
        parent_name: null,
        has_children: true,
        ad_account_id: "act_1",
        cabinet_timezone: "Europe/Kaliningrad",
        timezone_known: true,
        timezone_state: "single",
        offer_id: null,
        offer_code: null,
        state: "ready",
        issues: [],
        spend: "18.40",
        impressions: 420,
        clicks: 42,
        leads: 5,
        registrations: 5,
        ftds: 1,
        confirmed_deposits: 1,
        redeposits: 0,
        revenue: "25.00",
        cpc: "0.4381",
        ctr_pct: "10.00",
        click_registration_cr_pct: "11.90",
        registration_ftd_cr_pct: "20.00",
        cost_per_registration: "3.6800",
        cost_per_ftd: "18.4000",
        roi_pct: "35.87",
        roas: "1.3587",
        live_budget: null,
        budget_unavailable_reason: null,
      },
    ],
  };
}
