apiVersion: v1
kind: Service
metadata:
  name: fb-stop-bot-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fb-stop-bot.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    {{- include "fb-stop-bot.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - port: 8100
      targetPort: 8100
      name: http
