apiVersion: apps/v1
kind: Deployment
metadata:
  name: fb-stop-bot-mini-app
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fb-stop-bot.labels" . | nindent 4 }}
    app.kubernetes.io/component: mini-app
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "fb-stop-bot.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mini-app
  template:
    metadata:
      labels:
        {{- include "fb-stop-bot.labels" . | nindent 8 }}
        app.kubernetes.io/component: mini-app
    spec:
      containers:
        - name: mini-app
          image: "{{ .Values.image.registry }}/{{ .Values.image.miniApp.repository }}:{{ .Values.image.miniApp.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
              name: http
          readinessProbe:
            httpGet:
              path: /tma/
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources.frontend | nindent 12 }}
