apiVersion: v1
kind: Secret
metadata:
  name: fb-stop-bot-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fb-stop-bot.labels" . | nindent 4 }}
type: Opaque
stringData:
  API_KEY: {{ .Values.secrets.apiKey | quote }}
  TELEGRAM_BOT_TOKEN: {{ .Values.secrets.telegramBotToken | quote }}
  VISION_X_TOKEN: {{ .Values.secrets.visionXToken | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  OWNER_TELEGRAM_USER_ID: {{ .Values.secrets.ownerTelegramUserId | quote }}
  TMA_SECRET_KEY: {{ .Values.secrets.tmaSecretKey | quote }}
