/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatsIndexRouteImport } from './routes/stats/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as RemoteDesktopIndexRouteImport } from './routes/remote-desktop/index'
import { Route as OffersIndexRouteImport } from './routes/offers/index'
import { Route as HistoryIndexRouteImport } from './routes/history/index'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns/index'
import { Route as AnalyticsIndexRouteImport } from './routes/analytics/index'
import { Route as AdsIndexRouteImport } from './routes/ads/index'
import { Route as OffersIdRouteImport } from './routes/offers/$id'
import { Route as AdsFbAdIdRouteImport } from './routes/ads/$fbAdId'
import { Route as CampaignsCreateIndexRouteImport } from './routes/campaigns/create/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsIndexRoute = StatsIndexRouteImport.update({
  id: '/stats/',
  path: '/stats/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const RemoteDesktopIndexRoute = RemoteDesktopIndexRouteImport.update({
  id: '/remote-desktop/',
  path: '/remote-desktop/',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersIndexRoute = OffersIndexRouteImport.update({
  id: '/offers/',
  path: '/offers/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsIndexRoute = AnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsIndexRoute = AdsIndexRouteImport.update({
  id: '/ads/',
  path: '/ads/',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersIdRoute = OffersIdRouteImport.update({
  id: '/offers/$id',
  path: '/offers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsFbAdIdRoute = AdsFbAdIdRouteImport.update({
  id: '/ads/$fbAdId',
  path: '/ads/$fbAdId',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCreateIndexRoute = CampaignsCreateIndexRouteImport.update({
  id: '/campaigns/create/',
  path: '/campaigns/create/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ads/$fbAdId': typeof AdsFbAdIdRoute
  '/offers/$id': typeof OffersIdRoute
  '/ads/': typeof AdsIndexRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/history/': typeof HistoryIndexRoute
  '/offers/': typeof OffersIndexRoute
  '/remote-desktop/': typeof RemoteDesktopIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/stats/': typeof StatsIndexRoute
  '/campaigns/create/': typeof CampaignsCreateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ads/$fbAdId': typeof AdsFbAdIdRoute
  '/offers/$id': typeof OffersIdRoute
  '/ads': typeof AdsIndexRoute
  '/analytics': typeof AnalyticsIndexRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/history': typeof HistoryIndexRoute
  '/offers': typeof OffersIndexRoute
  '/remote-desktop': typeof RemoteDesktopIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/stats': typeof StatsIndexRoute
  '/campaigns/create': typeof CampaignsCreateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ads/$fbAdId': typeof AdsFbAdIdRoute
  '/offers/$id': typeof OffersIdRoute
  '/ads/': typeof AdsIndexRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/history/': typeof HistoryIndexRoute
  '/offers/': typeof OffersIndexRoute
  '/remote-desktop/': typeof RemoteDesktopIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/stats/': typeof StatsIndexRoute
  '/campaigns/create/': typeof CampaignsCreateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ads/$fbAdId'
    | '/offers/$id'
    | '/ads/'
    | '/analytics/'
    | '/campaigns/'
    | '/history/'
    | '/offers/'
    | '/remote-desktop/'
    | '/settings/'
    | '/stats/'
    | '/campaigns/create/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ads/$fbAdId'
    | '/offers/$id'
    | '/ads'
    | '/analytics'
    | '/campaigns'
    | '/history'
    | '/offers'
    | '/remote-desktop'
    | '/settings'
    | '/stats'
    | '/campaigns/create'
  id:
    | '__root__'
    | '/'
    | '/ads/$fbAdId'
    | '/offers/$id'
    | '/ads/'
    | '/analytics/'
    | '/campaigns/'
    | '/history/'
    | '/offers/'
    | '/remote-desktop/'
    | '/settings/'
    | '/stats/'
    | '/campaigns/create/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdsFbAdIdRoute: typeof AdsFbAdIdRoute
  OffersIdRoute: typeof OffersIdRoute
  AdsIndexRoute: typeof AdsIndexRoute
  AnalyticsIndexRoute: typeof AnalyticsIndexRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
  OffersIndexRoute: typeof OffersIndexRoute
  RemoteDesktopIndexRoute: typeof RemoteDesktopIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  StatsIndexRoute: typeof StatsIndexRoute
  CampaignsCreateIndexRoute: typeof CampaignsCreateIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/': {
      id: '/stats/'
      path: '/stats'
      fullPath: '/stats/'
      preLoaderRoute: typeof StatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remote-desktop/': {
      id: '/remote-desktop/'
      path: '/remote-desktop'
      fullPath: '/remote-desktop/'
      preLoaderRoute: typeof RemoteDesktopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers/': {
      id: '/offers/'
      path: '/offers'
      fullPath: '/offers/'
      preLoaderRoute: typeof OffersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/': {
      id: '/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof HistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/': {
      id: '/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads/': {
      id: '/ads/'
      path: '/ads'
      fullPath: '/ads/'
      preLoaderRoute: typeof AdsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers/$id': {
      id: '/offers/$id'
      path: '/offers/$id'
      fullPath: '/offers/$id'
      preLoaderRoute: typeof OffersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads/$fbAdId': {
      id: '/ads/$fbAdId'
      path: '/ads/$fbAdId'
      fullPath: '/ads/$fbAdId'
      preLoaderRoute: typeof AdsFbAdIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/create/': {
      id: '/campaigns/create/'
      path: '/campaigns/create'
      fullPath: '/campaigns/create/'
      preLoaderRoute: typeof CampaignsCreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdsFbAdIdRoute: AdsFbAdIdRoute,
  OffersIdRoute: OffersIdRoute,
  AdsIndexRoute: AdsIndexRoute,
  AnalyticsIndexRoute: AnalyticsIndexRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
  HistoryIndexRoute: HistoryIndexRoute,
  OffersIndexRoute: OffersIndexRoute,
  RemoteDesktopIndexRoute: RemoteDesktopIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  StatsIndexRoute: StatsIndexRoute,
  CampaignsCreateIndexRoute: CampaignsCreateIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
