# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from . import ad_library_pb2 as v1_dot_ad__library__pb2

GRPC_GENERATED_VERSION = "1.80.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in v1/ad_library_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class AdLibraryServiceStub(object):
    """AdLibraryService — поиск рекламы в Meta Ad Library через активную Vision-сессию.

    Архитектурная заметка: публичный Ad Library API (через токен) НЕ покрывает наши
    GEO (Африка/LatAm/Турция — outside EU/UK). Standalone scraper'ы (curl_cffi,
    requests) моментально rate-limit'ятся Meta по IP/fingerprint.

    Поэтому работает session-tunneling: browser-agent открывает Ad Library страницу
    в новой вкладке той же Vision-сессии (где уже залогинен Facebook), перехватывает
    GraphQL responses и возвращает ads через gRPC. Meta видит залогиненного юзера,
    rate-limit мягкий.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchAds = channel.unary_unary(
            "/fb_agent.ad_library.v1.AdLibraryService/SearchAds",
            request_serializer=v1_dot_ad__library__pb2.SearchAdsRequest.SerializeToString,
            response_deserializer=v1_dot_ad__library__pb2.SearchAdsResponse.FromString,
            _registered_method=True,
        )
        self.SearchAdsBatch = channel.unary_unary(
            "/fb_agent.ad_library.v1.AdLibraryService/SearchAdsBatch",
            request_serializer=v1_dot_ad__library__pb2.SearchAdsBatchRequest.SerializeToString,
            response_deserializer=v1_dot_ad__library__pb2.SearchAdsBatchResponse.FromString,
            _registered_method=True,
        )
        self.CheckAdLibraryHealth = channel.unary_unary(
            "/fb_agent.ad_library.v1.AdLibraryService/CheckAdLibraryHealth",
            request_serializer=v1_dot_ad__library__pb2.CheckAdLibraryHealthRequest.SerializeToString,
            response_deserializer=v1_dot_ad__library__pb2.CheckAdLibraryHealthResponse.FromString,
            _registered_method=True,
        )


class AdLibraryServiceServicer(object):
    """AdLibraryService — поиск рекламы в Meta Ad Library через активную Vision-сессию.

    Архитектурная заметка: публичный Ad Library API (через токен) НЕ покрывает наши
    GEO (Африка/LatAm/Турция — outside EU/UK). Standalone scraper'ы (curl_cffi,
    requests) моментально rate-limit'ятся Meta по IP/fingerprint.

    Поэтому работает session-tunneling: browser-agent открывает Ad Library страницу
    в новой вкладке той же Vision-сессии (где уже залогинен Facebook), перехватывает
    GraphQL responses и возвращает ads через gRPC. Meta видит залогиненного юзера,
    rate-limit мягкий.
    """

    def SearchAds(self, request, context):
        """Поиск ads по keyword + country. Возвращает массив raw GraphQL ads
        (структура сохранена для гибкого парсинга на Python-стороне).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SearchAdsBatch(self, request, context):
        """Batch-поиск: открывает Ad Library один раз для country, прогоняет все
        queries через input.fill() (как реальный юзер), возвращает результаты пачкой.
        Это стабильнее чем серия SearchAds — Meta не блокирует повторные fetch
        потому что юзер "печатает" в input, а не делает goto на новый URL.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CheckAdLibraryHealth(self, request, context):
        """Проверить готовность канала: жив ли browser context, доступна ли Ad Library.
        Не делает реальных запросов к Meta — только проверка окружения.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_AdLibraryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "SearchAds": grpc.unary_unary_rpc_method_handler(
            servicer.SearchAds,
            request_deserializer=v1_dot_ad__library__pb2.SearchAdsRequest.FromString,
            response_serializer=v1_dot_ad__library__pb2.SearchAdsResponse.SerializeToString,
        ),
        "SearchAdsBatch": grpc.unary_unary_rpc_method_handler(
            servicer.SearchAdsBatch,
            request_deserializer=v1_dot_ad__library__pb2.SearchAdsBatchRequest.FromString,
            response_serializer=v1_dot_ad__library__pb2.SearchAdsBatchResponse.SerializeToString,
        ),
        "CheckAdLibraryHealth": grpc.unary_unary_rpc_method_handler(
            servicer.CheckAdLibraryHealth,
            request_deserializer=v1_dot_ad__library__pb2.CheckAdLibraryHealthRequest.FromString,
            response_serializer=v1_dot_ad__library__pb2.CheckAdLibraryHealthResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "fb_agent.ad_library.v1.AdLibraryService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "fb_agent.ad_library.v1.AdLibraryService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class AdLibraryService(object):
    """AdLibraryService — поиск рекламы в Meta Ad Library через активную Vision-сессию.

    Архитектурная заметка: публичный Ad Library API (через токен) НЕ покрывает наши
    GEO (Африка/LatAm/Турция — outside EU/UK). Standalone scraper'ы (curl_cffi,
    requests) моментально rate-limit'ятся Meta по IP/fingerprint.

    Поэтому работает session-tunneling: browser-agent открывает Ad Library страницу
    в новой вкладке той же Vision-сессии (где уже залогинен Facebook), перехватывает
    GraphQL responses и возвращает ads через gRPC. Meta видит залогиненного юзера,
    rate-limit мягкий.
    """

    @staticmethod
    def SearchAds(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/fb_agent.ad_library.v1.AdLibraryService/SearchAds",
            v1_dot_ad__library__pb2.SearchAdsRequest.SerializeToString,
            v1_dot_ad__library__pb2.SearchAdsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SearchAdsBatch(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/fb_agent.ad_library.v1.AdLibraryService/SearchAdsBatch",
            v1_dot_ad__library__pb2.SearchAdsBatchRequest.SerializeToString,
            v1_dot_ad__library__pb2.SearchAdsBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CheckAdLibraryHealth(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/fb_agent.ad_library.v1.AdLibraryService/CheckAdLibraryHealth",
            v1_dot_ad__library__pb2.CheckAdLibraryHealthRequest.SerializeToString,
            v1_dot_ad__library__pb2.CheckAdLibraryHealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
