# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from . import browser_session_pb2 as v1_dot_browser__session__pb2

GRPC_GENERATED_VERSION = "1.80.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in v1/browser_session_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class BrowserSessionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartBrowser = channel.unary_unary(
            "/fb_agent.browser_session.v1.BrowserSessionService/StartBrowser",
            request_serializer=v1_dot_browser__session__pb2.StartBrowserRequest.SerializeToString,
            response_deserializer=v1_dot_browser__session__pb2.StartBrowserResponse.FromString,
            _registered_method=True,
        )
        self.DisconnectBrowser = channel.unary_unary(
            "/fb_agent.browser_session.v1.BrowserSessionService/DisconnectBrowser",
            request_serializer=v1_dot_browser__session__pb2.DisconnectBrowserRequest.SerializeToString,
            response_deserializer=v1_dot_browser__session__pb2.DisconnectBrowserResponse.FromString,
            _registered_method=True,
        )
        self.StopBrowser = channel.unary_unary(
            "/fb_agent.browser_session.v1.BrowserSessionService/StopBrowser",
            request_serializer=v1_dot_browser__session__pb2.StopBrowserRequest.SerializeToString,
            response_deserializer=v1_dot_browser__session__pb2.StopBrowserResponse.FromString,
            _registered_method=True,
        )
        self.ReconnectBrowser = channel.unary_unary(
            "/fb_agent.browser_session.v1.BrowserSessionService/ReconnectBrowser",
            request_serializer=v1_dot_browser__session__pb2.ReconnectBrowserRequest.SerializeToString,
            response_deserializer=v1_dot_browser__session__pb2.StartBrowserResponse.FromString,
            _registered_method=True,
        )
        self.GetSessionInfo = channel.unary_unary(
            "/fb_agent.browser_session.v1.BrowserSessionService/GetSessionInfo",
            request_serializer=v1_dot_browser__session__pb2.GetSessionInfoRequest.SerializeToString,
            response_deserializer=v1_dot_browser__session__pb2.GetSessionInfoResponse.FromString,
            _registered_method=True,
        )
        self.Navigate = channel.unary_unary(
            "/fb_agent.browser_session.v1.BrowserSessionService/Navigate",
            request_serializer=v1_dot_browser__session__pb2.NavigateRequest.SerializeToString,
            response_deserializer=v1_dot_browser__session__pb2.NavigateResponse.FromString,
            _registered_method=True,
        )
        self.OpenCabinetTabs = channel.unary_unary(
            "/fb_agent.browser_session.v1.BrowserSessionService/OpenCabinetTabs",
            request_serializer=v1_dot_browser__session__pb2.OpenCabinetTabsRequest.SerializeToString,
            response_deserializer=v1_dot_browser__session__pb2.OpenCabinetTabsResponse.FromString,
            _registered_method=True,
        )
        self.StreamSessionStatus = channel.unary_stream(
            "/fb_agent.browser_session.v1.BrowserSessionService/StreamSessionStatus",
            request_serializer=v1_dot_browser__session__pb2.StreamSessionStatusRequest.SerializeToString,
            response_deserializer=v1_dot_browser__session__pb2.SessionStatusEvent.FromString,
            _registered_method=True,
        )


class BrowserSessionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartBrowser(self, request, context):
        """Запустить Vision профиль и подключиться через CDP.
        Возвращает session_id для всех последующих вызовов.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DisconnectBrowser(self, request, context):
        """Отключиться от браузера (закрыть CDP, не останавливая Vision профиль)."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StopBrowser(self, request, context):
        """Полностью остановить Vision профиль (disconnect + stop profile)."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ReconnectBrowser(self, request, context):
        """Переподключиться после разрыва или ошибки."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetSessionInfo(self, request, context):
        """Получить информацию о сессии (URL, контексты, страницы)."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Navigate(self, request, context):
        """Перейти на URL."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def OpenCabinetTabs(self, request, context):
        """Открыть вкладки Ads Manager для списка кабинетов (фаза "подготовка рабочего
        места" перед сканом). Для каждого ad_account_id ищет/открывает вкладку кабинета
        (manage/campaigns + колонки). Не сканирует. Идемпотентно: уже открытую переиспользует.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StreamSessionStatus(self, request, context):
        """Стриминг статусов сессии (heartbeat, ошибки, смена страницы)."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_BrowserSessionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "StartBrowser": grpc.unary_unary_rpc_method_handler(
            servicer.StartBrowser,
            request_deserializer=v1_dot_browser__session__pb2.StartBrowserRequest.FromString,
            response_serializer=v1_dot_browser__session__pb2.StartBrowserResponse.SerializeToString,
        ),
        "DisconnectBrowser": grpc.unary_unary_rpc_method_handler(
            servicer.DisconnectBrowser,
            request_deserializer=v1_dot_browser__session__pb2.DisconnectBrowserRequest.FromString,
            response_serializer=v1_dot_browser__session__pb2.DisconnectBrowserResponse.SerializeToString,
        ),
        "StopBrowser": grpc.unary_unary_rpc_method_handler(
            servicer.StopBrowser,
            request_deserializer=v1_dot_browser__session__pb2.StopBrowserRequest.FromString,
            response_serializer=v1_dot_browser__session__pb2.StopBrowserResponse.SerializeToString,
        ),
        "ReconnectBrowser": grpc.unary_unary_rpc_method_handler(
            servicer.ReconnectBrowser,
            request_deserializer=v1_dot_browser__session__pb2.ReconnectBrowserRequest.FromString,
            response_serializer=v1_dot_browser__session__pb2.StartBrowserResponse.SerializeToString,
        ),
        "GetSessionInfo": grpc.unary_unary_rpc_method_handler(
            servicer.GetSessionInfo,
            request_deserializer=v1_dot_browser__session__pb2.GetSessionInfoRequest.FromString,
            response_serializer=v1_dot_browser__session__pb2.GetSessionInfoResponse.SerializeToString,
        ),
        "Navigate": grpc.unary_unary_rpc_method_handler(
            servicer.Navigate,
            request_deserializer=v1_dot_browser__session__pb2.NavigateRequest.FromString,
            response_serializer=v1_dot_browser__session__pb2.NavigateResponse.SerializeToString,
        ),
        "OpenCabinetTabs": grpc.unary_unary_rpc_method_handler(
            servicer.OpenCabinetTabs,
            request_deserializer=v1_dot_browser__session__pb2.OpenCabinetTabsRequest.FromString,
            response_serializer=v1_dot_browser__session__pb2.OpenCabinetTabsResponse.SerializeToString,
        ),
        "StreamSessionStatus": grpc.unary_stream_rpc_method_handler(
            servicer.StreamSessionStatus,
            request_deserializer=v1_dot_browser__session__pb2.StreamSessionStatusRequest.FromString,
            response_serializer=v1_dot_browser__session__pb2.SessionStatusEvent.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "fb_agent.browser_session.v1.BrowserSessionService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "fb_agent.browser_session.v1.BrowserSessionService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class BrowserSessionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartBrowser(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/fb_agent.browser_session.v1.BrowserSessionService/StartBrowser",
            v1_dot_browser__session__pb2.StartBrowserRequest.SerializeToString,
            v1_dot_browser__session__pb2.StartBrowserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DisconnectBrowser(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/fb_agent.browser_session.v1.BrowserSessionService/DisconnectBrowser",
            v1_dot_browser__session__pb2.DisconnectBrowserRequest.SerializeToString,
            v1_dot_browser__session__pb2.DisconnectBrowserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def StopBrowser(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/fb_agent.browser_session.v1.BrowserSessionService/StopBrowser",
            v1_dot_browser__session__pb2.StopBrowserRequest.SerializeToString,
            v1_dot_browser__session__pb2.StopBrowserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ReconnectBrowser(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/fb_agent.browser_session.v1.BrowserSessionService/ReconnectBrowser",
            v1_dot_browser__session__pb2.ReconnectBrowserRequest.SerializeToString,
            v1_dot_browser__session__pb2.StartBrowserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetSessionInfo(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/fb_agent.browser_session.v1.BrowserSessionService/GetSessionInfo",
            v1_dot_browser__session__pb2.GetSessionInfoRequest.SerializeToString,
            v1_dot_browser__session__pb2.GetSessionInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Navigate(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/fb_agent.browser_session.v1.BrowserSessionService/Navigate",
            v1_dot_browser__session__pb2.NavigateRequest.SerializeToString,
            v1_dot_browser__session__pb2.NavigateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def OpenCabinetTabs(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/fb_agent.browser_session.v1.BrowserSessionService/OpenCabinetTabs",
            v1_dot_browser__session__pb2.OpenCabinetTabsRequest.SerializeToString,
            v1_dot_browser__session__pb2.OpenCabinetTabsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def StreamSessionStatus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/fb_agent.browser_session.v1.BrowserSessionService/StreamSessionStatus",
            v1_dot_browser__session__pb2.StreamSessionStatusRequest.SerializeToString,
            v1_dot_browser__session__pb2.SessionStatusEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
