# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from . import browser_session_pb2 as v1_dot_browser__session__pb2

GRPC_GENERATED_VERSION = "1.80.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in v1/browser_session_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class BrowserSessionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartBrowser = channel.unary_unary(
            "/fb_agent.browser_session.v1.BrowserSessionService/StartBrowser",
            request_serializer=v1_dot_browser__session__pb2.StartBrowserRequest.SerializeToString,
            response_deserializer=v1_dot_browser__session__pb2.StartBrowserResponse.FromString,
            _registered_method=True,
        )
        self.ReconnectBrowser = channel.unary_unary(
            "/fb_agent.browser_session.v1.BrowserSessionService/ReconnectBrowser",
            request_serializer=v1_dot_browser__session__pb2.ReconnectBrowserRequest.SerializeToString,
            response_deserializer=v1_dot_browser__session__pb2.StartBrowserResponse.FromString,
            _registered_method=True,
        )
        self.RecoverBrowserProfileUnderMaintenance = channel.unary_unary(
            "/fb_agent.browser_session.v1.BrowserSessionService/RecoverBrowserProfileUnderMaintenance",
            request_serializer=v1_dot_browser__session__pb2.RecoverBrowserProfileRequest.SerializeToString,
            response_deserializer=v1_dot_browser__session__pb2.StartBrowserResponse.FromString,
            _registered_method=True,
        )
        self.OpenCabinetTabs = channel.unary_unary(
            "/fb_agent.browser_session.v1.BrowserSessionService/OpenCabinetTabs",
            request_serializer=v1_dot_browser__session__pb2.OpenCabinetTabsRequest.SerializeToString,
            response_deserializer=v1_dot_browser__session__pb2.OpenCabinetTabsResponse.FromString,
            _registered_method=True,
        )


class BrowserSessionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartBrowser(self, request, context):
        """Создать process-local browser-agent сессию, подключившись только к уже
        живому Vision CDP. Этот RPC никогда не запускает и не рестартует профиль.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ReconnectBrowser(self, request, context):
        """Переподключиться после разрыва или ошибки."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RecoverBrowserProfileUnderMaintenance(self, request, context):
        """Принудительно перезапустить canonical Vision-профиль и подключиться заново.
        Вызывается только API control plane после проверки PostgreSQL maintenance lease.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def OpenCabinetTabs(self, request, context):
        """Открыть вкладки Ads Manager для списка кабинетов (фаза "подготовка рабочего
        места" перед сканом). Для каждого ad_account_id ищет/открывает вкладку кабинета
        (manage/campaigns + колонки). Не сканирует. Идемпотентно: уже открытую переиспользует.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_BrowserSessionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "StartBrowser": grpc.unary_unary_rpc_method_handler(
            servicer.StartBrowser,
            request_deserializer=v1_dot_browser__session__pb2.StartBrowserRequest.FromString,
            response_serializer=v1_dot_browser__session__pb2.StartBrowserResponse.SerializeToString,
        ),
        "ReconnectBrowser": grpc.unary_unary_rpc_method_handler(
            servicer.ReconnectBrowser,
            request_deserializer=v1_dot_browser__session__pb2.ReconnectBrowserRequest.FromString,
            response_serializer=v1_dot_browser__session__pb2.StartBrowserResponse.SerializeToString,
        ),
        "RecoverBrowserProfileUnderMaintenance": grpc.unary_unary_rpc_method_handler(
            servicer.RecoverBrowserProfileUnderMaintenance,
            request_deserializer=v1_dot_browser__session__pb2.RecoverBrowserProfileRequest.FromString,
            response_serializer=v1_dot_browser__session__pb2.StartBrowserResponse.SerializeToString,
        ),
        "OpenCabinetTabs": grpc.unary_unary_rpc_method_handler(
            servicer.OpenCabinetTabs,
            request_deserializer=v1_dot_browser__session__pb2.OpenCabinetTabsRequest.FromString,
            response_serializer=v1_dot_browser__session__pb2.OpenCabinetTabsResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "fb_agent.browser_session.v1.BrowserSessionService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "fb_agent.browser_session.v1.BrowserSessionService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class BrowserSessionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartBrowser(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/fb_agent.browser_session.v1.BrowserSessionService/StartBrowser",
            v1_dot_browser__session__pb2.StartBrowserRequest.SerializeToString,
            v1_dot_browser__session__pb2.StartBrowserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ReconnectBrowser(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/fb_agent.browser_session.v1.BrowserSessionService/ReconnectBrowser",
            v1_dot_browser__session__pb2.ReconnectBrowserRequest.SerializeToString,
            v1_dot_browser__session__pb2.StartBrowserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def RecoverBrowserProfileUnderMaintenance(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/fb_agent.browser_session.v1.BrowserSessionService/RecoverBrowserProfileUnderMaintenance",
            v1_dot_browser__session__pb2.RecoverBrowserProfileRequest.SerializeToString,
            v1_dot_browser__session__pb2.StartBrowserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def OpenCabinetTabs(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/fb_agent.browser_session.v1.BrowserSessionService/OpenCabinetTabs",
            v1_dot_browser__session__pb2.OpenCabinetTabsRequest.SerializeToString,
            v1_dot_browser__session__pb2.OpenCabinetTabsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
