# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from . import creator_pb2 as v1_dot_creator__pb2

GRPC_GENERATED_VERSION = "1.80.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in v1/creator_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class CreatorServiceStub(object):
    """Сервис создания FB-кампаний: выполнение планов и запись новых через recorder.
    Работает поверх browser-agent-сессии (см. browser_session.proto).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunPlan = channel.unary_stream(
            "/fb_agent.creator.v1.CreatorService/RunPlan",
            request_serializer=v1_dot_creator__pb2.RunPlanRequest.SerializeToString,
            response_deserializer=v1_dot_creator__pb2.PlanEvent.FromString,
            _registered_method=True,
        )
        self.StartRecording = channel.unary_unary(
            "/fb_agent.creator.v1.CreatorService/StartRecording",
            request_serializer=v1_dot_creator__pb2.StartRecordingRequest.SerializeToString,
            response_deserializer=v1_dot_creator__pb2.StartRecordingResponse.FromString,
            _registered_method=True,
        )
        self.StopRecording = channel.unary_unary(
            "/fb_agent.creator.v1.CreatorService/StopRecording",
            request_serializer=v1_dot_creator__pb2.StopRecordingRequest.SerializeToString,
            response_deserializer=v1_dot_creator__pb2.StopRecordingResponse.FromString,
            _registered_method=True,
        )
        self.GetRecorderStatus = channel.unary_unary(
            "/fb_agent.creator.v1.CreatorService/GetRecorderStatus",
            request_serializer=v1_dot_creator__pb2.GetRecorderStatusRequest.SerializeToString,
            response_deserializer=v1_dot_creator__pb2.GetRecorderStatusResponse.FromString,
            _registered_method=True,
        )


class CreatorServiceServicer(object):
    """Сервис создания FB-кампаний: выполнение планов и запись новых через recorder.
    Работает поверх browser-agent-сессии (см. browser_session.proto).
    """

    def RunPlan(self, request, context):
        """Выполнить план: стримит события каждого шага (started/finished/failed/skipped)
        плюс финальный complete с итоговым статусом.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StartRecording(self, request, context):
        """Начать запись действий пользователя в Plan-формате. Возвращается сразу,
        recorder работает в браузере до StopRecording.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StopRecording(self, request, context):
        """Остановить запись и вернуть собранный Plan (JSON-строка)."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetRecorderStatus(self, request, context):
        """Получить текущее состояние recorder (для UI/polling). Не останавливает."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_CreatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "RunPlan": grpc.unary_stream_rpc_method_handler(
            servicer.RunPlan,
            request_deserializer=v1_dot_creator__pb2.RunPlanRequest.FromString,
            response_serializer=v1_dot_creator__pb2.PlanEvent.SerializeToString,
        ),
        "StartRecording": grpc.unary_unary_rpc_method_handler(
            servicer.StartRecording,
            request_deserializer=v1_dot_creator__pb2.StartRecordingRequest.FromString,
            response_serializer=v1_dot_creator__pb2.StartRecordingResponse.SerializeToString,
        ),
        "StopRecording": grpc.unary_unary_rpc_method_handler(
            servicer.StopRecording,
            request_deserializer=v1_dot_creator__pb2.StopRecordingRequest.FromString,
            response_serializer=v1_dot_creator__pb2.StopRecordingResponse.SerializeToString,
        ),
        "GetRecorderStatus": grpc.unary_unary_rpc_method_handler(
            servicer.GetRecorderStatus,
            request_deserializer=v1_dot_creator__pb2.GetRecorderStatusRequest.FromString,
            response_serializer=v1_dot_creator__pb2.GetRecorderStatusResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "fb_agent.creator.v1.CreatorService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("fb_agent.creator.v1.CreatorService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class CreatorService(object):
    """Сервис создания FB-кампаний: выполнение планов и запись новых через recorder.
    Работает поверх browser-agent-сессии (см. browser_session.proto).
    """

    @staticmethod
    def RunPlan(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/fb_agent.creator.v1.CreatorService/RunPlan",
            v1_dot_creator__pb2.RunPlanRequest.SerializeToString,
            v1_dot_creator__pb2.PlanEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def StartRecording(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/fb_agent.creator.v1.CreatorService/StartRecording",
            v1_dot_creator__pb2.StartRecordingRequest.SerializeToString,
            v1_dot_creator__pb2.StartRecordingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def StopRecording(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/fb_agent.creator.v1.CreatorService/StopRecording",
            v1_dot_creator__pb2.StopRecordingRequest.SerializeToString,
            v1_dot_creator__pb2.StopRecordingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetRecorderStatus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/fb_agent.creator.v1.CreatorService/GetRecorderStatus",
            v1_dot_creator__pb2.GetRecorderStatusRequest.SerializeToString,
            v1_dot_creator__pb2.GetRecorderStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
