# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from . import meta_api_pb2 as v1_dot_meta__api__pb2

GRPC_GENERATED_VERSION = "1.80.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in v1/meta_api_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class MetaApiServiceStub(object):
    """MetaApiService — мост к Marketing API через активную Vision-сессию.

    Архитектурная заметка: вызовы Marketing API НЕ исполняются standalone из Python,
    потому что EAAB-токены Ads Manager привязаны к browser session (machine_id, datr cookie,
    fingerprint). Anti-fraud Meta отвергает любые server-to-server вызовы с этими токенами.
    Поэтому весь Marketing API проходит ЧЕРЕЗ Playwright-страницу: browser-agent делает
    page.evaluate(fetch(...)) — запрос идёт из того же session-context, что и DOM-парсинг.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteGraphCall = channel.unary_unary(
            "/fb_agent.meta_api.v1.MetaApiService/ExecuteGraphCall",
            request_serializer=v1_dot_meta__api__pb2.ExecuteGraphCallRequest.SerializeToString,
            response_deserializer=v1_dot_meta__api__pb2.ExecuteGraphCallResponse.FromString,
            _registered_method=True,
        )
        self.CheckMetaApiHealth = channel.unary_unary(
            "/fb_agent.meta_api.v1.MetaApiService/CheckMetaApiHealth",
            request_serializer=v1_dot_meta__api__pb2.CheckMetaApiHealthRequest.SerializeToString,
            response_deserializer=v1_dot_meta__api__pb2.CheckMetaApiHealthResponse.FromString,
            _registered_method=True,
        )


class MetaApiServiceServicer(object):
    """MetaApiService — мост к Marketing API через активную Vision-сессию.

    Архитектурная заметка: вызовы Marketing API НЕ исполняются standalone из Python,
    потому что EAAB-токены Ads Manager привязаны к browser session (machine_id, datr cookie,
    fingerprint). Anti-fraud Meta отвергает любые server-to-server вызовы с этими токенами.
    Поэтому весь Marketing API проходит ЧЕРЕЗ Playwright-страницу: browser-agent делает
    page.evaluate(fetch(...)) — запрос идёт из того же session-context, что и DOM-парсинг.
    """

    def ExecuteGraphCall(self, request, context):
        """Универсальный wrapper. Исполняет произвольный Graph API endpoint
        изнутри активной браузерной сессии Ads Manager.

        Path формат: "/me", "/act_XXX/insights", "/{ad_id}", "/{campaign_id}/copies" и т.д.
        Параметры в query_params, тело в body_json.
        access_token подставляется автоматически из page source.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CheckMetaApiHealth(self, request, context):
        """Проверить готовность Marketing API канала: жива ли Vision-сессия,
        на правильной ли странице (Ads Manager), извлекается ли токен.
        Лёгкий запрос — используется в health_watchdog для мониторинга.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_MetaApiServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ExecuteGraphCall": grpc.unary_unary_rpc_method_handler(
            servicer.ExecuteGraphCall,
            request_deserializer=v1_dot_meta__api__pb2.ExecuteGraphCallRequest.FromString,
            response_serializer=v1_dot_meta__api__pb2.ExecuteGraphCallResponse.SerializeToString,
        ),
        "CheckMetaApiHealth": grpc.unary_unary_rpc_method_handler(
            servicer.CheckMetaApiHealth,
            request_deserializer=v1_dot_meta__api__pb2.CheckMetaApiHealthRequest.FromString,
            response_serializer=v1_dot_meta__api__pb2.CheckMetaApiHealthResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "fb_agent.meta_api.v1.MetaApiService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "fb_agent.meta_api.v1.MetaApiService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class MetaApiService(object):
    """MetaApiService — мост к Marketing API через активную Vision-сессию.

    Архитектурная заметка: вызовы Marketing API НЕ исполняются standalone из Python,
    потому что EAAB-токены Ads Manager привязаны к browser session (machine_id, datr cookie,
    fingerprint). Anti-fraud Meta отвергает любые server-to-server вызовы с этими токенами.
    Поэтому весь Marketing API проходит ЧЕРЕЗ Playwright-страницу: browser-agent делает
    page.evaluate(fetch(...)) — запрос идёт из того же session-context, что и DOM-парсинг.
    """

    @staticmethod
    def ExecuteGraphCall(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/fb_agent.meta_api.v1.MetaApiService/ExecuteGraphCall",
            v1_dot_meta__api__pb2.ExecuteGraphCallRequest.SerializeToString,
            v1_dot_meta__api__pb2.ExecuteGraphCallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CheckMetaApiHealth(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/fb_agent.meta_api.v1.MetaApiService/CheckMetaApiHealth",
            v1_dot_meta__api__pb2.CheckMetaApiHealthRequest.SerializeToString,
            v1_dot_meta__api__pb2.CheckMetaApiHealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
