# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/meta_api.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "v1/meta_api.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x11v1/meta_api.proto\x12\x14\x66\x62_agent.meta_api.v1"\x94\x02\n\x17\x45xecuteGraphCallRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0e\n\x06method\x18\x02 \x01(\t\x12\x10\n\x08\x65ndpoint\x18\x03 \x01(\t\x12T\n\x0cquery_params\x18\x04 \x03(\x0b\x32>.fb_agent.meta_api.v1.ExecuteGraphCallRequest.QueryParamsEntry\x12\x11\n\tbody_json\x18\x05 \x01(\t\x12\x17\n\ntimeout_ms\x18\x06 \x01(\x05H\x00\x88\x01\x01\x1a\x32\n\x10QueryParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\r\n\x0b_timeout_ms"\x9e\x01\n\x18\x45xecuteGraphCallResponse\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\x12\x15\n\rresponse_json\x18\x02 \x01(\t\x12\x13\n\x0b\x64uration_ms\x18\x03 \x01(\x05\x12\x37\n\x05\x65rror\x18\x04 \x01(\x0b\x32#.fb_agent.meta_api.v1.GraphApiErrorH\x00\x88\x01\x01\x42\x08\n\x06_error"a\n\rGraphApiError\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07subcode\x18\x02 \x01(\x05\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\x12\x12\n\nfbtrace_id\x18\x05 \x01(\t"/\n\x19\x43heckMetaApiHealthRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t"\x7f\n\x1a\x43heckMetaApiHealthResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x13\n\x0b\x63urrent_url\x18\x02 \x01(\t\x12\x15\n\rtoken_present\x18\x03 \x01(\x08\x12\x14\n\x0ctoken_length\x18\x04 \x01(\x05\x12\x0e\n\x06\x64\x65tail\x18\x05 \x01(\t2\xfc\x01\n\x0eMetaApiService\x12q\n\x10\x45xecuteGraphCall\x12-.fb_agent.meta_api.v1.ExecuteGraphCallRequest\x1a..fb_agent.meta_api.v1.ExecuteGraphCallResponse\x12w\n\x12\x43heckMetaApiHealth\x12/.fb_agent.meta_api.v1.CheckMetaApiHealthRequest\x1a\x30.fb_agent.meta_api.v1.CheckMetaApiHealthResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "v1.meta_api_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_EXECUTEGRAPHCALLREQUEST_QUERYPARAMSENTRY"]._loaded_options = None
    _globals["_EXECUTEGRAPHCALLREQUEST_QUERYPARAMSENTRY"]._serialized_options = b"8\001"
    _globals["_EXECUTEGRAPHCALLREQUEST"]._serialized_start = 44
    _globals["_EXECUTEGRAPHCALLREQUEST"]._serialized_end = 320
    _globals["_EXECUTEGRAPHCALLREQUEST_QUERYPARAMSENTRY"]._serialized_start = 255
    _globals["_EXECUTEGRAPHCALLREQUEST_QUERYPARAMSENTRY"]._serialized_end = 305
    _globals["_EXECUTEGRAPHCALLRESPONSE"]._serialized_start = 323
    _globals["_EXECUTEGRAPHCALLRESPONSE"]._serialized_end = 481
    _globals["_GRAPHAPIERROR"]._serialized_start = 483
    _globals["_GRAPHAPIERROR"]._serialized_end = 580
    _globals["_CHECKMETAAPIHEALTHREQUEST"]._serialized_start = 582
    _globals["_CHECKMETAAPIHEALTHREQUEST"]._serialized_end = 629
    _globals["_CHECKMETAAPIHEALTHRESPONSE"]._serialized_start = 631
    _globals["_CHECKMETAAPIHEALTHRESPONSE"]._serialized_end = 758
    _globals["_METAAPISERVICE"]._serialized_start = 761
    _globals["_METAAPISERVICE"]._serialized_end = 1013
# @@protoc_insertion_point(module_scope)
