# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import scanner_pb2 as v1_dot_scanner__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in v1/scanner_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ScannerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunScanCycle = channel.unary_stream(
                '/fb_agent.scanner.v1.ScannerService/RunScanCycle',
                request_serializer=v1_dot_scanner__pb2.RunScanCycleRequest.SerializeToString,
                response_deserializer=v1_dot_scanner__pb2.ScanCycleEvent.FromString,
                _registered_method=True)
        self.ListCampaigns = channel.unary_unary(
                '/fb_agent.scanner.v1.ScannerService/ListCampaigns',
                request_serializer=v1_dot_scanner__pb2.ListCampaignsRequest.SerializeToString,
                response_deserializer=v1_dot_scanner__pb2.ListCampaignsResponse.FromString,
                _registered_method=True)


class ScannerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunScanCycle(self, request, context):
        """Полный цикл сканирования через am_tabular (graph-канал UI, active replication).
        Стримит один ScanComplete (DOM-парсинг/скролл выпилены).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCampaigns(self, request, context):
        """Live-список кампаний по owner_tag (через Graph campaigns edge, МИМО allowlist).
        Для UI «Кампании для сканирования»: показывает ВСЕ кампании владельца, включая
        новые, которые ещё не сканировались (allowlist их не пропускал бы в обычный скан).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScannerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunScanCycle': grpc.unary_stream_rpc_method_handler(
                    servicer.RunScanCycle,
                    request_deserializer=v1_dot_scanner__pb2.RunScanCycleRequest.FromString,
                    response_serializer=v1_dot_scanner__pb2.ScanCycleEvent.SerializeToString,
            ),
            'ListCampaigns': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCampaigns,
                    request_deserializer=v1_dot_scanner__pb2.ListCampaignsRequest.FromString,
                    response_serializer=v1_dot_scanner__pb2.ListCampaignsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fb_agent.scanner.v1.ScannerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fb_agent.scanner.v1.ScannerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ScannerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunScanCycle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/fb_agent.scanner.v1.ScannerService/RunScanCycle',
            v1_dot_scanner__pb2.RunScanCycleRequest.SerializeToString,
            v1_dot_scanner__pb2.ScanCycleEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCampaigns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fb_agent.scanner.v1.ScannerService/ListCampaigns',
            v1_dot_scanner__pb2.ListCampaignsRequest.SerializeToString,
            v1_dot_scanner__pb2.ListCampaignsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
