# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
from v1 import scanner_pb2 as v1_dot_scanner__pb2

GRPC_GENERATED_VERSION = "1.80.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in v1/scanner_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class ScannerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunScanCycle = channel.unary_stream(
            "/fb_agent.scanner.v1.ScannerService/RunScanCycle",
            request_serializer=v1_dot_scanner__pb2.RunScanCycleRequest.SerializeToString,
            response_deserializer=v1_dot_scanner__pb2.ScanCycleEvent.FromString,
            _registered_method=True,
        )
        self.RefreshTable = channel.unary_unary(
            "/fb_agent.scanner.v1.ScannerService/RefreshTable",
            request_serializer=v1_dot_scanner__pb2.RefreshTableRequest.SerializeToString,
            response_deserializer=v1_dot_scanner__pb2.RefreshTableResponse.FromString,
            _registered_method=True,
        )
        self.ParseVisibleRows = channel.unary_unary(
            "/fb_agent.scanner.v1.ScannerService/ParseVisibleRows",
            request_serializer=v1_dot_scanner__pb2.ParseVisibleRowsRequest.SerializeToString,
            response_deserializer=v1_dot_scanner__pb2.ParseVisibleRowsResponse.FromString,
            _registered_method=True,
        )
        self.ScrollAndParse = channel.unary_unary(
            "/fb_agent.scanner.v1.ScannerService/ScrollAndParse",
            request_serializer=v1_dot_scanner__pb2.ScrollAndParseRequest.SerializeToString,
            response_deserializer=v1_dot_scanner__pb2.ScrollAndParseResponse.FromString,
            _registered_method=True,
        )
        self.WaitForDomStable = channel.unary_unary(
            "/fb_agent.scanner.v1.ScannerService/WaitForDomStable",
            request_serializer=v1_dot_scanner__pb2.WaitForDomStableRequest.SerializeToString,
            response_deserializer=v1_dot_scanner__pb2.WaitForDomStableResponse.FromString,
            _registered_method=True,
        )
        self.ResetScroll = channel.unary_unary(
            "/fb_agent.scanner.v1.ScannerService/ResetScroll",
            request_serializer=v1_dot_scanner__pb2.ResetScrollRequest.SerializeToString,
            response_deserializer=v1_dot_scanner__pb2.ResetScrollResponse.FromString,
            _registered_method=True,
        )
        self.GetScrollMetrics = channel.unary_unary(
            "/fb_agent.scanner.v1.ScannerService/GetScrollMetrics",
            request_serializer=v1_dot_scanner__pb2.GetScrollMetricsRequest.SerializeToString,
            response_deserializer=v1_dot_scanner__pb2.GetScrollMetricsResponse.FromString,
            _registered_method=True,
        )
        self.GetVisibleRowIds = channel.unary_unary(
            "/fb_agent.scanner.v1.ScannerService/GetVisibleRowIds",
            request_serializer=v1_dot_scanner__pb2.GetVisibleRowIdsRequest.SerializeToString,
            response_deserializer=v1_dot_scanner__pb2.GetVisibleRowIdsResponse.FromString,
            _registered_method=True,
        )
        self.FindToggleCell = channel.unary_unary(
            "/fb_agent.scanner.v1.ScannerService/FindToggleCell",
            request_serializer=v1_dot_scanner__pb2.FindToggleCellRequest.SerializeToString,
            response_deserializer=v1_dot_scanner__pb2.FindToggleCellResponse.FromString,
            _registered_method=True,
        )
        self.ReadToggleState = channel.unary_unary(
            "/fb_agent.scanner.v1.ScannerService/ReadToggleState",
            request_serializer=v1_dot_scanner__pb2.ReadToggleStateRequest.SerializeToString,
            response_deserializer=v1_dot_scanner__pb2.ReadToggleStateResponse.FromString,
            _registered_method=True,
        )
        self.ToggleAd = channel.unary_unary(
            "/fb_agent.scanner.v1.ScannerService/ToggleAd",
            request_serializer=v1_dot_scanner__pb2.ToggleAdRequest.SerializeToString,
            response_deserializer=v1_dot_scanner__pb2.ToggleAdResponse.FromString,
            _registered_method=True,
        )
        self.HumanMove = channel.unary_unary(
            "/fb_agent.scanner.v1.ScannerService/HumanMove",
            request_serializer=v1_dot_scanner__pb2.HumanMoveRequest.SerializeToString,
            response_deserializer=v1_dot_scanner__pb2.HumanMoveResponse.FromString,
            _registered_method=True,
        )
        self.HumanClick = channel.unary_unary(
            "/fb_agent.scanner.v1.ScannerService/HumanClick",
            request_serializer=v1_dot_scanner__pb2.HumanClickRequest.SerializeToString,
            response_deserializer=v1_dot_scanner__pb2.HumanClickResponse.FromString,
            _registered_method=True,
        )
        self.HumanWheelScroll = channel.unary_unary(
            "/fb_agent.scanner.v1.ScannerService/HumanWheelScroll",
            request_serializer=v1_dot_scanner__pb2.HumanWheelScrollRequest.SerializeToString,
            response_deserializer=v1_dot_scanner__pb2.HumanWheelScrollResponse.FromString,
            _registered_method=True,
        )
        self.WaitForToggleConfirmation = channel.unary_unary(
            "/fb_agent.scanner.v1.ScannerService/WaitForToggleConfirmation",
            request_serializer=v1_dot_scanner__pb2.WaitForToggleConfirmationRequest.SerializeToString,
            response_deserializer=v1_dot_scanner__pb2.WaitForToggleConfirmationResponse.FromString,
            _registered_method=True,
        )
        self.ValidateColumns = channel.unary_unary(
            "/fb_agent.scanner.v1.ScannerService/ValidateColumns",
            request_serializer=v1_dot_scanner__pb2.ValidateColumnsRequest.SerializeToString,
            response_deserializer=v1_dot_scanner__pb2.ValidateColumnsResponse.FromString,
            _registered_method=True,
        )
        self.CaptureColumnWidths = channel.unary_unary(
            "/fb_agent.scanner.v1.ScannerService/CaptureColumnWidths",
            request_serializer=v1_dot_scanner__pb2.CaptureColumnWidthsRequest.SerializeToString,
            response_deserializer=v1_dot_scanner__pb2.CaptureColumnWidthsResponse.FromString,
            _registered_method=True,
        )
        self.ApplyColumnWidths = channel.unary_unary(
            "/fb_agent.scanner.v1.ScannerService/ApplyColumnWidths",
            request_serializer=v1_dot_scanner__pb2.ApplyColumnWidthsRequest.SerializeToString,
            response_deserializer=v1_dot_scanner__pb2.ApplyColumnWidthsResponse.FromString,
            _registered_method=True,
        )
        self.HardReloadPage = channel.unary_unary(
            "/fb_agent.scanner.v1.ScannerService/HardReloadPage",
            request_serializer=v1_dot_scanner__pb2.HardReloadPageRequest.SerializeToString,
            response_deserializer=v1_dot_scanner__pb2.HardReloadPageResponse.FromString,
            _registered_method=True,
        )


class ScannerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunScanCycle(self, request, context):
        """Полный цикл сканирования: reset scroll → refresh → settle → scroll-and-parse.
        Стримит частичные результаты (rows per pass).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RefreshTable(self, request, context):
        """Обновить таблицу Ads Manager (клик по кнопке "Refresh")."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ParseVisibleRows(self, request, context):
        """Распарсить видимые строки из текущего viewport (без скролла)."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ScrollAndParse(self, request, context):
        """Скроллить таблицу вниз и распарсить новые строки."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def WaitForDomStable(self, request, context):
        """Дождаться стабилизации DOM после скролла (количество строк перестаёт меняться)."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ResetScroll(self, request, context):
        """Сбросить позицию скролла таблицы наверх."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetScrollMetrics(self, request, context):
        """Получить текущие метрики скролла (scrollTop, maxScrollTop, atBottom)."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetVisibleRowIds(self, request, context):
        """Получить ID видимых строк в DOM."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def FindToggleCell(self, request, context):
        """Найти toggle-ячейку для конкретного объявления (скроллит таблицу)."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ReadToggleState(self, request, context):
        """Прочитать aria-checked состояние toggle-ячейки."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ToggleAd(self, request, context):
        """Переключить on/off switch объявления."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def HumanMove(self, request, context):
        """Human-like движение мыши к координатам."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def HumanClick(self, request, context):
        """Human-like клик по координатам."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def HumanWheelScroll(self, request, context):
        """Human-like скролл колесом."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def WaitForToggleConfirmation(self, request, context):
        """Ждать подтверждения toggle через повторные чтения aria-checked."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ValidateColumns(self, request, context):
        """Проверить наличие всех необходимых колонок в таблице Ads Manager."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CaptureColumnWidths(self, request, context):
        """Снять текущую ручную ширину колонок Ads Manager."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ApplyColumnWidths(self, request, context):
        """Применить сохранённый пресет ширины колонок Ads Manager."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def HardReloadPage(self, request, context):
        """Жёсткая перезагрузка страницы с очисткой кеша (через CDP Network.clearBrowserCache)."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ScannerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "RunScanCycle": grpc.unary_stream_rpc_method_handler(
            servicer.RunScanCycle,
            request_deserializer=v1_dot_scanner__pb2.RunScanCycleRequest.FromString,
            response_serializer=v1_dot_scanner__pb2.ScanCycleEvent.SerializeToString,
        ),
        "RefreshTable": grpc.unary_unary_rpc_method_handler(
            servicer.RefreshTable,
            request_deserializer=v1_dot_scanner__pb2.RefreshTableRequest.FromString,
            response_serializer=v1_dot_scanner__pb2.RefreshTableResponse.SerializeToString,
        ),
        "ParseVisibleRows": grpc.unary_unary_rpc_method_handler(
            servicer.ParseVisibleRows,
            request_deserializer=v1_dot_scanner__pb2.ParseVisibleRowsRequest.FromString,
            response_serializer=v1_dot_scanner__pb2.ParseVisibleRowsResponse.SerializeToString,
        ),
        "ScrollAndParse": grpc.unary_unary_rpc_method_handler(
            servicer.ScrollAndParse,
            request_deserializer=v1_dot_scanner__pb2.ScrollAndParseRequest.FromString,
            response_serializer=v1_dot_scanner__pb2.ScrollAndParseResponse.SerializeToString,
        ),
        "WaitForDomStable": grpc.unary_unary_rpc_method_handler(
            servicer.WaitForDomStable,
            request_deserializer=v1_dot_scanner__pb2.WaitForDomStableRequest.FromString,
            response_serializer=v1_dot_scanner__pb2.WaitForDomStableResponse.SerializeToString,
        ),
        "ResetScroll": grpc.unary_unary_rpc_method_handler(
            servicer.ResetScroll,
            request_deserializer=v1_dot_scanner__pb2.ResetScrollRequest.FromString,
            response_serializer=v1_dot_scanner__pb2.ResetScrollResponse.SerializeToString,
        ),
        "GetScrollMetrics": grpc.unary_unary_rpc_method_handler(
            servicer.GetScrollMetrics,
            request_deserializer=v1_dot_scanner__pb2.GetScrollMetricsRequest.FromString,
            response_serializer=v1_dot_scanner__pb2.GetScrollMetricsResponse.SerializeToString,
        ),
        "GetVisibleRowIds": grpc.unary_unary_rpc_method_handler(
            servicer.GetVisibleRowIds,
            request_deserializer=v1_dot_scanner__pb2.GetVisibleRowIdsRequest.FromString,
            response_serializer=v1_dot_scanner__pb2.GetVisibleRowIdsResponse.SerializeToString,
        ),
        "FindToggleCell": grpc.unary_unary_rpc_method_handler(
            servicer.FindToggleCell,
            request_deserializer=v1_dot_scanner__pb2.FindToggleCellRequest.FromString,
            response_serializer=v1_dot_scanner__pb2.FindToggleCellResponse.SerializeToString,
        ),
        "ReadToggleState": grpc.unary_unary_rpc_method_handler(
            servicer.ReadToggleState,
            request_deserializer=v1_dot_scanner__pb2.ReadToggleStateRequest.FromString,
            response_serializer=v1_dot_scanner__pb2.ReadToggleStateResponse.SerializeToString,
        ),
        "ToggleAd": grpc.unary_unary_rpc_method_handler(
            servicer.ToggleAd,
            request_deserializer=v1_dot_scanner__pb2.ToggleAdRequest.FromString,
            response_serializer=v1_dot_scanner__pb2.ToggleAdResponse.SerializeToString,
        ),
        "HumanMove": grpc.unary_unary_rpc_method_handler(
            servicer.HumanMove,
            request_deserializer=v1_dot_scanner__pb2.HumanMoveRequest.FromString,
            response_serializer=v1_dot_scanner__pb2.HumanMoveResponse.SerializeToString,
        ),
        "HumanClick": grpc.unary_unary_rpc_method_handler(
            servicer.HumanClick,
            request_deserializer=v1_dot_scanner__pb2.HumanClickRequest.FromString,
            response_serializer=v1_dot_scanner__pb2.HumanClickResponse.SerializeToString,
        ),
        "HumanWheelScroll": grpc.unary_unary_rpc_method_handler(
            servicer.HumanWheelScroll,
            request_deserializer=v1_dot_scanner__pb2.HumanWheelScrollRequest.FromString,
            response_serializer=v1_dot_scanner__pb2.HumanWheelScrollResponse.SerializeToString,
        ),
        "WaitForToggleConfirmation": grpc.unary_unary_rpc_method_handler(
            servicer.WaitForToggleConfirmation,
            request_deserializer=v1_dot_scanner__pb2.WaitForToggleConfirmationRequest.FromString,
            response_serializer=v1_dot_scanner__pb2.WaitForToggleConfirmationResponse.SerializeToString,
        ),
        "ValidateColumns": grpc.unary_unary_rpc_method_handler(
            servicer.ValidateColumns,
            request_deserializer=v1_dot_scanner__pb2.ValidateColumnsRequest.FromString,
            response_serializer=v1_dot_scanner__pb2.ValidateColumnsResponse.SerializeToString,
        ),
        "CaptureColumnWidths": grpc.unary_unary_rpc_method_handler(
            servicer.CaptureColumnWidths,
            request_deserializer=v1_dot_scanner__pb2.CaptureColumnWidthsRequest.FromString,
            response_serializer=v1_dot_scanner__pb2.CaptureColumnWidthsResponse.SerializeToString,
        ),
        "ApplyColumnWidths": grpc.unary_unary_rpc_method_handler(
            servicer.ApplyColumnWidths,
            request_deserializer=v1_dot_scanner__pb2.ApplyColumnWidthsRequest.FromString,
            response_serializer=v1_dot_scanner__pb2.ApplyColumnWidthsResponse.SerializeToString,
        ),
        "HardReloadPage": grpc.unary_unary_rpc_method_handler(
            servicer.HardReloadPage,
            request_deserializer=v1_dot_scanner__pb2.HardReloadPageRequest.FromString,
            response_serializer=v1_dot_scanner__pb2.HardReloadPageResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "fb_agent.scanner.v1.ScannerService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("fb_agent.scanner.v1.ScannerService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class ScannerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunScanCycle(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/fb_agent.scanner.v1.ScannerService/RunScanCycle",
            v1_dot_scanner__pb2.RunScanCycleRequest.SerializeToString,
            v1_dot_scanner__pb2.ScanCycleEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def RefreshTable(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/fb_agent.scanner.v1.ScannerService/RefreshTable",
            v1_dot_scanner__pb2.RefreshTableRequest.SerializeToString,
            v1_dot_scanner__pb2.RefreshTableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ParseVisibleRows(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/fb_agent.scanner.v1.ScannerService/ParseVisibleRows",
            v1_dot_scanner__pb2.ParseVisibleRowsRequest.SerializeToString,
            v1_dot_scanner__pb2.ParseVisibleRowsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ScrollAndParse(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/fb_agent.scanner.v1.ScannerService/ScrollAndParse",
            v1_dot_scanner__pb2.ScrollAndParseRequest.SerializeToString,
            v1_dot_scanner__pb2.ScrollAndParseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def WaitForDomStable(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/fb_agent.scanner.v1.ScannerService/WaitForDomStable",
            v1_dot_scanner__pb2.WaitForDomStableRequest.SerializeToString,
            v1_dot_scanner__pb2.WaitForDomStableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ResetScroll(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/fb_agent.scanner.v1.ScannerService/ResetScroll",
            v1_dot_scanner__pb2.ResetScrollRequest.SerializeToString,
            v1_dot_scanner__pb2.ResetScrollResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetScrollMetrics(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/fb_agent.scanner.v1.ScannerService/GetScrollMetrics",
            v1_dot_scanner__pb2.GetScrollMetricsRequest.SerializeToString,
            v1_dot_scanner__pb2.GetScrollMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetVisibleRowIds(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/fb_agent.scanner.v1.ScannerService/GetVisibleRowIds",
            v1_dot_scanner__pb2.GetVisibleRowIdsRequest.SerializeToString,
            v1_dot_scanner__pb2.GetVisibleRowIdsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def FindToggleCell(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/fb_agent.scanner.v1.ScannerService/FindToggleCell",
            v1_dot_scanner__pb2.FindToggleCellRequest.SerializeToString,
            v1_dot_scanner__pb2.FindToggleCellResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ReadToggleState(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/fb_agent.scanner.v1.ScannerService/ReadToggleState",
            v1_dot_scanner__pb2.ReadToggleStateRequest.SerializeToString,
            v1_dot_scanner__pb2.ReadToggleStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ToggleAd(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/fb_agent.scanner.v1.ScannerService/ToggleAd",
            v1_dot_scanner__pb2.ToggleAdRequest.SerializeToString,
            v1_dot_scanner__pb2.ToggleAdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def HumanMove(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/fb_agent.scanner.v1.ScannerService/HumanMove",
            v1_dot_scanner__pb2.HumanMoveRequest.SerializeToString,
            v1_dot_scanner__pb2.HumanMoveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def HumanClick(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/fb_agent.scanner.v1.ScannerService/HumanClick",
            v1_dot_scanner__pb2.HumanClickRequest.SerializeToString,
            v1_dot_scanner__pb2.HumanClickResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def HumanWheelScroll(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/fb_agent.scanner.v1.ScannerService/HumanWheelScroll",
            v1_dot_scanner__pb2.HumanWheelScrollRequest.SerializeToString,
            v1_dot_scanner__pb2.HumanWheelScrollResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def WaitForToggleConfirmation(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/fb_agent.scanner.v1.ScannerService/WaitForToggleConfirmation",
            v1_dot_scanner__pb2.WaitForToggleConfirmationRequest.SerializeToString,
            v1_dot_scanner__pb2.WaitForToggleConfirmationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ValidateColumns(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/fb_agent.scanner.v1.ScannerService/ValidateColumns",
            v1_dot_scanner__pb2.ValidateColumnsRequest.SerializeToString,
            v1_dot_scanner__pb2.ValidateColumnsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CaptureColumnWidths(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/fb_agent.scanner.v1.ScannerService/CaptureColumnWidths",
            v1_dot_scanner__pb2.CaptureColumnWidthsRequest.SerializeToString,
            v1_dot_scanner__pb2.CaptureColumnWidthsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ApplyColumnWidths(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/fb_agent.scanner.v1.ScannerService/ApplyColumnWidths",
            v1_dot_scanner__pb2.ApplyColumnWidthsRequest.SerializeToString,
            v1_dot_scanner__pb2.ApplyColumnWidthsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def HardReloadPage(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/fb_agent.scanner.v1.ScannerService/HardReloadPage",
            v1_dot_scanner__pb2.HardReloadPageRequest.SerializeToString,
            v1_dot_scanner__pb2.HardReloadPageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
