from __future__ import annotations

from enum import StrEnum


class DeliveryStatus(StrEnum):
    ACTIVE = "ACTIVE"
    LEARNING = "LEARNING"
    PAUSED = "PAUSED"
    NOT_DELIVERING = "NOT_DELIVERING"
    UNKNOWN = "UNKNOWN"


class TrackingMode(StrEnum):
    TRACKED = "TRACKED"
    MANUAL_BLOCK = "MANUAL_BLOCK"
    READ_ONLY = "READ_ONLY"
    ARCHIVED = "ARCHIVED"


class ScopePresence(StrEnum):
    IN_SCOPE = "IN_SCOPE"
    NOT_SEEN_THIS_SCAN = "NOT_SEEN_THIS_SCAN"
    OUT_OF_SCOPE_CONFIRMED = "OUT_OF_SCOPE_CONFIRMED"


class DecisionType(StrEnum):
    NO_ACTION = "NO_ACTION"
    WOULD_PAUSE = "WOULD_PAUSE"
    WOULD_RESUME = "WOULD_RESUME"
    SKIPPED_BY_POLICY = "SKIPPED_BY_POLICY"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    AMBIGUOUS = "AMBIGUOUS"
    ALERT_REJECTION = "ALERT_REJECTION"
    KEPT_PAUSED_BY_VIABILITY = "KEPT_PAUSED_BY_VIABILITY"


class ActionType(StrEnum):
    PAUSE = "PAUSE"
    RESUME = "RESUME"


class ActionExecutionStatus(StrEnum):
    PENDING = "PENDING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"


class TelegramEventType(StrEnum):
    AD_PAUSED_BY_BOT = "AD_PAUSED_BY_BOT"
    AD_RESUMED_BY_BOT = "AD_RESUMED_BY_BOT"
    AD_REJECTED_OR_NOT_DELIVERING = "AD_REJECTED_OR_NOT_DELIVERING"
    OBSERVE_WOULD_PAUSE = "OBSERVE_WOULD_PAUSE"
    OBSERVE_WOULD_RESUME = "OBSERVE_WOULD_RESUME"
    WORKER_ERROR = "WORKER_ERROR"
    SCOPE_INVALID = "SCOPE_INVALID"


class EntityType(StrEnum):
    CAMPAIGN = "campaign"
    ADSET = "adset"
    AD = "ad"


class ScanRunStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    INVALID = "INVALID"
